TeamSparker/Spark-iOS

.gitignore

[DOCS] gitignore파일 추가

---

README.md

🌱 작업한 브랜치
- docs/#5
🌱 작업한 내용
- 중간과제에 맞춰 리드미 수정했습니다
- Resolved: #5

[Docs] #5 - 리드미 수정

---

Spark-iOS/Podfile
Spark-iOS/Podfile.lock
Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS.xcworkspace/contents.xcworkspacedata

🌱 작업한 브랜치
- feature/#4
🌱 작업한 내용
- 코코아팟 설치
- 라이브러리 인스톨
+ snapkit
+ JJFloatingActionButton
+ kingfisher
+ swiftlint
+ moya
+ KakaoSDK
- 라이브러리 인스톨 완료했습니다.
- Resolved: #4

[Add] #4 - CocoaPods install

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#13
🌱 작업한 내용
- 앱 이름 변경. Spark
- 번들 아이디 변경. com.Team-Sparker.Spark
- Develpment_Team 변경.
- DEPLOYMENT_TARGET 변경. 15.0
- MARKETING_VERSION. 1.0.0
- 번들 아이디: 앱의 고유 아이디
- Development team: 개발자 계정을 등록.
- Deployment target: 요구되는 최소 버전.
> 참고: [iOS Deployment Target](https://adervise1.tistory.com/104)
- Marketing version: 앱의 버전이다.
- Resolved: #13

[Chore] #13 - 앱 이름 변경 및 프로젝트 설정

---

Spark-iOS/Spark-iOS/Resource/Info.plist

🌱 작업한 브랜치
- feature/#30
🌱 작업한 내용
- Korea 언어 추가
|기능|스크린샷|
|:--:|:--:|
|GIF|<img width="500" alt="스크린샷 2022-01-13 오전 5 45 23" src="https://user-images.githubusercontent.com/69136340/149218808-742b5da9-f989-4de8-9025-cb30297e8855.png">|
- Resolved: #30

[Feat] #30 - 언어 추가

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/ResetPopupVC.swift

🌱 작업한 브랜치
- feature/#70
🌱 작업한 내용
- 스톱워치 처음 시작할 때 버튼 숨기고, 하단의 버튼에 스톱워치 시작 연결해줬습니다
|기능|스크린샷|
|:--:|:--:|
| 위잉 | <img src="https://user-images.githubusercontent.com/81167570/149645920-c7fbcbe0-e3e4-41aa-bc49-045e5cee8939.jpeg" width="40%" /> |
- Resolved: #75

[Chore] #75 - 스톱워치 뷰 처음 시작 수정

---

Spark-iOS/.swiftlint.yml
Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/AppDelegate.swift
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
Spark-iOS/Spark-iOS/Source/Extensions/UIView+.swift
Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Plugin/MoyaLoggerPlugin.swift
Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#65
🌱 작업한 내용
- 에... 수정된 부분보면서 학습 부탁드립니다 ㅎㅎ
- 최대한 워닝없이 코드 작성 부탁드릴게요!
- 서버통신 붙일때 강제추출 코드를 제거하면서 swiflint 에서 봐주고있던 옵션을 제거할게용 그러면 강제추출은 일부 케이스빼고 에러가 뜨게 될거에용
- swiftLint 를 통해서 우리가 놓치고 있던 컨밴션들을 잡아보았습니당! 꼭 다 읽어주시고 코딩 부탁드릴겡요~
- Resolved: #65

[Add] #65 - SwiftLint 적용

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Room/CreateRoom.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Room/RoomId.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingRoom.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
Spark-iOS/Spark-iOS/Source/Protocols/TempProtocol.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#100
🌱 작업한 내용
- 습관방 생성 서버 연결
- 연결 후 대기방으로 roomID 전달해서 수정
. . . . . .
|기능|스크린샷|
|:--:|:--:|
| 습관방이 만들고 싶어? |  ![ezgif com-gif-maker (37)](https://user-images.githubusercontent.com/81167570/149907312-d3903cf5-3075-4bcf-a435-bd3d5830154a.gif)  |
- Resolved: #100

[Feat] #100 - 습관방 생성 서버 연결

---

Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.xib
Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift

🌱 작업한 브랜치
- feature/#103
🌱 작업한 내용
- 홈에서 life 가 3초과인경우 예외처리
- 대기방 티켓 이미지 추가
- 대기방 "다른 스파커를 기다리는 중..." bottom constraint 설정
스플래시에서 현재 무조건 메인으로 보내는 중. 수정할 것
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src ="https://user-images.githubusercontent.com/69136340/149908680-0e1cf489-f02d-4d46-b8f5-e068de45b517.jpeg" width ="250">|
- Resolved: #103

[Feat] #103 - 홈뷰 대기방 티켓 이미지 설정

---

Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift

🌱 작업한 브랜치
- feature/#119
🌱 작업한 내용
- 쉴래요 고민중 서버 연결
- authType에 따라 인증 종류 이미지 변경
- 습관방 서버 연결 후 정보 전달받아서 분기처리 마저 하겠습니다.
- 쉴래요 남은 횟수가 0인 경우 버튼 비활성화시키기
- Resolved: #119

[Feat] #119 - 쉴래요 고민중 서버 연결

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
Spark-iOS/Spark-iOS/Resource/Storyboards/Profile/ProfileSetting.storyboard
Spark-iOS/Spark-iOS/Source/Extensions/UILabel+.swift
Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#115
🌱 작업한 내용
- 레이아웃
- 텍스트필드
- 이미지 선택 액션시트
UILabel+의 함수를 조금 더 재사용하기 좋게 수정했습니다
하나는 특정 부분 폰트를 바꿀 수 있는 함수이고, 하나는 특정 부분 컬러를 바꿀 수 있는 함수입니다!
|기능|스크린샷|
|:--:|:--:|
| 프로필 설정 뷰 |  ![ezgif com-gif-maker (39)](https://user-images.githubusercontent.com/81167570/150004374-e3a73639-6866-4ad5-b85f-ac73053e9d9b.gif)  |
- Resolved: #115

[Feat] #115 - 프로필 설정 뷰 레이아웃

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
Spark-iOS/Spark-iOS/Resource/Info.plist
Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/ResetPopupVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
Spark-iOS/Spark-iOS/Source/Views/CreateAuth/PhotoAuthView.swift
Spark-iOS/Spark-iOS/Source/Views/CreateAuth/TimerAuthView.swift

🌱 작업한 브랜치
- feature/#72
- feature/#115 
(중간에 잠시 잘못 다녀왔습니다..)
🌱 작업한 내용
-  타이머 단위 수정
-  타이머 분기처리
-  사진 업로드 하단 버튼 플로우, 멘트 변경
-  피드뷰 한 번에 7-10개씩
- 뷰 멘트 수정(`ProfileSetting`, `CreateRoom`, `CreateAuth`, `AuthTimer`, `ResetPopup`, `AuthUpload`, `GoalWriting`, `Waiting`, `PhotoAuthView`, `TimerAuthView`)
|기능|스크린샷|
|:--:|:--:|
| 타이머 수정 | ![ezgif com-gif-maker (40)](https://user-images.githubusercontent.com/81167570/150088003-b6fb2306-e769-43f6-ae11-19258fca92ee.gif) |
| 사진업로드 하단 플로우 수정 | ![ezgif com-gif-maker (41)](https://user-images.githubusercontent.com/81167570/150091660-60818386-1efe-4dcc-89a1-e3a66234fa2d.gif)  |
- Resolved: #72

[Feat] #72 - 뷰 디테일 수정

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
Spark-iOS/Spark-iOS/Resource/Info.plist
Spark-iOS/Spark-iOS/Source/AppDelegate.swift

🌱 작업한 브랜치
- feature/#116
🌱 작업한 내용
- 다크모드 막기
- 세로모드 고정
|기능|스크린샷|
|:--:|:--:|
| 다크모드 막고 세로모드 고정 | 생략 |
- Resolved: #116

[Feat] #116 - 다크모드 막기, 세로모드 고정

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift

🌱 작업한 브랜치
- feature/#135
🌱 작업한 내용
- 테스트 플라이트용 빌드숫자 올리기
- 시작 뷰컨 변경
- Resolved: #135

[Chore] #135 - 빌드 숫자 업데이트(2) 및 시작 뷰컨 변경

---

Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedEmptyCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeEmptyCVC.xib
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.xib
Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift

🌱 작업한 브랜치
- feature/#139
🌱 작업한 내용
- 홈 엠티뷰 스크롤 막기
- 홈 엠티뷰 레이아웃 수정
- 엠티뷰 컬러 변경
- 멘트 수정 반영
|기능|스크린샷|
|:--:|:--:|
| 홈 엠티뷰 |![IMG_5779](https://user-images.githubusercontent.com/81167570/150302479-8045508f-9c47-4b73-9dcb-9e241bb8dd89.PNG)  |
| 피드 엠티뷰 | ![IMG_7B6CF4FBADFB-1](https://user-images.githubusercontent.com/81167570/150302494-6f9287cf-87b7-4376-9f45-badfc175a231.jpeg) |
- Resolved: #139

[Fix] #139 - 홈 엠티뷰 스크롤 막기

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#152
🌱 작업한 내용
- 위를 해결하기 위해서 메인탭바를 네비게이션으로 띄우던것을 수정.
- 기존의 홈VC를 별도로 메인탭바에서 네비게이션컨트롤러로 띄움
- Resolved: #152

[Feat] #152 - 앱전반의 네비바 설정

---

Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift

🌱 작업한 브랜치
- feature/#157
🌱 작업한 내용
- 습관 인증 후 화면전환
- 코드로 참여, 인증 완료, 습관 인증 팝업뷰 하단 버튼 높이 통일
|기능|스크린샷|
|:--:|:--:|
|생략|생략|
- Resolved: #157

[Feat] #157 - 습관 인증 후 피드로 화면 전환

---

Spark-iOS/Spark-iOS/Resource/Info.plist
Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift

🌱 작업한 브랜치
- feature/#166
🌱 작업한 내용
- 이미지 리사이징 기기대응
- 쉴래요 고민중 버튼 분기처리
- 인스타 공유 부분 주석처리 했습니다.
- Resolved: #166

[Chore] #166 - 이미지 리사이징 기기대응 및 쉴래요 고민중 버튼 분기처리

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift

🌱 작업한 브랜치
- feature/#176
🌱 작업한 내용
- `습관에 불을 지펴봐!` 로 문구 변경
- Resolved: #176

[Fix] #176 - 스플래쉬 문구 변경

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#179
🌱 작업한 내용
- 작업내용
- 작업내용
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #이슈번호

[Fix] 홈 플로팅버튼 사라지는 문제해결

---

Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

🌱 작업한 브랜치
- feature/#186
🌱 작업한 내용
- 습관방 초기상태 세팅 및 홈 폰트 수정
- 습관방 상세보기 로딩창 추가(인증하기 갔다가 쉴래요, 고민중 할 경우에 로딩창 등장)
- Resolved: #186

[Feat] #186 - 습관방 초기상태 세팅 및 홈 폰트 수정, 습관방 상세보기 로딩창 추가

---

Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard

🌱 작업한 브랜치
- feature/#193
🌱 작업한 내용
- 습관방 양쪽 흰배경 수정(검은배경으로 설정)
- 디데이 텍스트를 좀더 위로 올렸습니다
- Resolved: #193

[Fix] #193 - 습관방 양쪽 흰배경수정, 레이아웃 수정

---

Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
Spark-iOS/Spark-iOS/Source/Protocols/FeedCellDelegate.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift

🌱 작업한 브랜치
- feature/#197
🌱 작업한 내용
- 피드뷰 하트 로컬 반영
- Resolved: #197

[Feat] #197 - 피드뷰 하트 로컬 반영

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift

인스타 투터치 현상 해결
🌱 작업한 브랜치
- feature/#200
🌱 작업한 내용
- 인스타 투터치 현상 해결
- Resolved: #200

[Feat] #200 - 인스타 투터치 현상 해결

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#196
🌱 작업한 내용
- 대기방에서 홈으로 화면전환 수정
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #196

[Fix] #196 - 대기방에서 홈으로 화면전환 수정

---

Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.xib
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

🌱 작업한 브랜치
- feature/#203
🌱 작업한 내용
- 습관방 티켓 잘리던 에러 해결
- Resolved: #203

[Fix] #203 - 습관방 티켓 잘리던 에러

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#207
🌱 작업한 내용
- 대기방 tooltip 버튼 레이아웃 수정
- 방생성 로딩창 추가
|기능|스크린샷|
|:--:|:--:|
|아주 미세한 수정| <img src="https://user-images.githubusercontent.com/81167570/151185575-70dcf55c-a5ec-48a1-9e0c-e68c3ac49700.jpeg" width="40%" />  |
- Resolved: #207

[Feat] #207 - 대기방 tooltip 레이아웃 수정 및 방생성 로딩창 추가

---

Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift

🌱 작업한 브랜치
- feature/#213
🌱 작업한 내용
- day62 대신 day65 였던 분기처리를 수정해줌
- Resolved: #213

[Fix] #213 - SparkFlake 날짜 day62 분기처리 수정

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

🌱 작업한 브랜치
- feature/#228
🌱 작업한 내용
```swift
navigationController?.interactivePopGestureRecognizer?.delegate = nil
```
- 해당 코드는 root view controller 에서 스와이프 pop 제스처를 취하면 버그가 생기기 때문에 리펙토링 진행했습니다.
- root view controller 의 경우에는  스와이프 pop 제스처를 무효화 처리
> 아직은 우리 프로젝트는 rootViewController 에서 다른 제스처도 있어서 그런지.. 모르겠지만 back swipe gesture 를 취해도 문제가 없지만 다른 프로젝트를 만들어서 진행해본 결과 확실히 버그가 나왔어요! 그래서 이렇게 리팩토링합니다.
> https://potent-piccolo-507.notion.site/iOS-pop-enable-back-swipe-gesture-4087d26c27784b71991613769dad6e0e
노션으로 보는 것이 편할것 같아서 위에 이렇게 자세한 설명과 함께 정리해두었습니다!
> 티스토리: https://gyuios.tistory.com/147
- Resolved: #228

[Refactor] #228 - 스와이프해서 pop 코드 리펙토링 

---

Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift

🌱 작업한 브랜치
- feature/#225
🌱 작업한 내용
- 인증사진 모아보기 뷰에서 타이머 인증의 경우 타이머 라벨과 투명도를 가진 UIView 추가
- timerCount의 존재 유무에 따라 분기처리
- 아직은 서버에서 값을 주지 않기에 일단 initcell에서 timerCount의 값을 nil로 줘 놨습니다.
- 추후 timer 값을 다시 넣어주는 작업이 필요합니다.
- Resolved: #225

[Feat] #225 - 인증사진 모아보기 뷰 타이머 인증 분기처리

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedEmptyCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedFooterView.swift
Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedHeaderView.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift

🌱 작업한 브랜치
- feature/#230
🌱 작업한 내용
- 피드뷰의 footer 추가했습니다
- 피드의 마지막 리스트 전에는 loading이 보이고, 마지막 리스트에선 마지막이라는 멘트가 보이도록 했습니다.
행복하십니까 다들?
일단 여러 방향으로 코드를 짜보다가 제 나름대로 최대한 자연스러운 방향으로 만들었고 코드에 주석도 달아놨습니다!
그럼에도 불구하고 어색하다면 알려주세요..!
|기능|스크린샷|
|:--:|:--:|
| 애증의 피드 .. |  ![ezgif com-gif-maker (46)](https://user-images.githubusercontent.com/81167570/152353288-23b4b983-93b3-4dd3-8b2c-981574f1421e.gif)   |
- Resolved: #230

[Feat] #230 - 피드에 footer 추가

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#234
🌱 작업한 내용
- 피드에 footer 추가, 좋아요 로티 문제 해결
- 인증사진 모아보기 뷰 타이머 인증 분기처리 및 REST 이미지 정렬 수정, 보관함 셀 증식 해결
- 습관방에서 멤버 상태스티커 반영
- 대기방 툴팁 레이아웃 수정 및 방생성 로딩창 추가
- 및 에러 해결
#207 #210 #214 #226 #225 #230
#213 #216 #209 #221 #223 
#228
- Resolved: #234

[Chore] #234 - 빌드 버전 변경(6)

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#237
🌱 작업한 내용
- #231 
- Resolved: #237

[Chore] #237 - 빌드 버전 변경(7)

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift

🌱 작업한 브랜치
- feature/#248
🌱 작업한 내용
- 텍스트필드 레이아웃 수정 (CreateRoomVC, GoalWritingVC, ProfileSettingVC)
텍스트필드가 사용되는 세가지 VC 전부 수정했습니다.
꼭 앞의 풀리퀘 #247 를 머지한 뒤 확인해주세요..!
|기능|스크린샷|
|:--:|:--:|
| ... |   <img src="https://user-images.githubusercontent.com/81167570/153451422-312f9b0c-0ce0-4e9c-9ceb-aca6a6005e7d.jpeg" width="40%" /> |
- Resolved: #248

[Fix] #248 - 습관방 생성 뷰 텍스트필드 레이아웃 수정

---

Spark-iOS/.swiftlint.yml
Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift

🌱 작업한 브랜치
- feature/#242
🌱 작업한 내용
- 습관방 티켓 폰트수정(폰트가 설정이 안되어있었어서 설정해둠)
- 인증하기 바텀시트 문구 수정
|기능|스크린샷|
|:--:|:--:|
|습관방 티켓|<img src="https://user-images.githubusercontent.com/69136340/153612502-50fce911-3f56-40c8-a9eb-65b949fbf0dc.jpeg" width ="250">|
|습관방 인증|<img src="https://user-images.githubusercontent.com/69136340/153613315-2ec09d2f-89d4-4d18-a097-150d4ddf585f.jpeg" width ="250">|
- Resolved: #242

[FIX] #242 - 습관방 티켓 폰트수정 및 인증하기 바텀시트 문구 수정

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#272
🌱 작업한 내용
- 습관방, 대기방, 보관함, 피드 등 QA 진행
- 대기방, 보관함, 피드 등 리펙토링
- 피드 footer 마지막 멘트가 중간에 보이는 버그 해결
- 플로팅 버튼 라이브러리 재설치
> 해당 오픈 라이브러리를 fork 해서 branch 를 만들어서 사용 
#239 #241 #244 #248 #242 #253 #250 #259 #246 #263 #267 #266 #265
#252
#257 
- Resolved: #272

[Chore] #272 - 빌드 버전 변경(8)

---

Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
Spark-iOS/Spark-iOS/Source/NetworkModels/MyRoom/MyRoomCerti.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift

인증사진 모아보기 타이머 표시 기능 연결
🌱 작업한 브랜치
- feature/#274
🌱 작업한 내용
- 모델 변경
- initcell 함수 내용 변경
- 폰트 변경
아래 첨부한 사진에 타이머가 뜨는 방이 있고 안 뜨는 방이 있는데, 서버에서 임의로 중간에 방 인증 타입을 바꾼 방이라 그렇습니다...
|기능|스크린샷|
|:--:|:--:|
|인증사진 모아보기|<img src="https://user-images.githubusercontent.com/77208067/154307083-7c6315b3-78b0-497f-b11c-32c0295385d5.png" width="40%" />|
- Resolved: #274

[Fix] #274 - 인증사진 모아보기 타이머 표시 기능 연결

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

🌱 작업한 브랜치
- feature/#280
🌱 작업한 내용
#258
#274
- Resolved: #280

[Chore] #280 - 빌드 버전 변경(9)

---

Spark-iOS/Spark-iOS/Source/Extensions/UIFont+.swift

🌱 작업한 브랜치
- feature/#286
🌱 작업한 내용
- 타이포 추가
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #286

[Add] #286 - UIFont+ 타이포 추가

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/Classes/SparkActionSheet.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift

커스텀 액션시트 구현 및 인증사진 모아보기 cornerRadius 적용
⛳️ **작업한 브랜치**
- feature/#284
- feature/#298
👷 **작업한 내용**
- 커스텀 액션시트 구현
- 인증사진 모아보기 cornerRadius 적용
- 커스텀 액션시트를 적용 완료한 뷰
-  인증사진 모아보기(StorageMore)
-  프로필세팅(ProfileSetting)
-  습관방 인증(HabitRoom)
-  습관방 더보기(HabitRoom)
-  인증하기 플로우(AuthUpload)
커스텀 액션시트를 구현하기 위해 총 4개의 클래스를 구성했습니다.
- SparkActionMainStackView를 띄울 뷰컨트롤러 클래스
- SparkSection과 SectionSpacer를 담아줄 스택뷰 클래스
- SparkAction과 ActionSpacer를 담아줄 스택뷰 클래스
- 실질적으로 버튼 액션을 구현할 버튼 클래스
```
let alert = SparkActionSheet()
alert.addAction(SparkAction("나의 목표 수정", titleType: .blackMediumTitle, handler: {
print("나의 목표 수정 뷰로 전환")
}))
alert.addAction(SparkAction("방 나가기", titleType: .pinkMediumTitle, handler: {
print("방 나가기 뷰로 전환")
}))
alert.addSection()
alert.addAction(SparkAction("취소", titleType: .blackBoldTitle, …
```

[Feat] #284, #298 - 커스텀 액션시트 구현

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoomLeave.storyboard
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomLeaveVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

⛳️ **작업한 브랜치**
- feature/#305
👷 **작업한 내용**
- 대기방 삭제 (방장)
- 대기방 나가기 (참여자)
- 습관방 나가기 (방장, 참여자)
이제 돔황칠 수 있습니다 돔황차
파일 이름들이 먼가 쫌 제각각인 것 같어요...
나중에 한번 싹.. 밀어벌여..? 아니아니 참자
|기능|스크린샷|
|:--:|:--:|
- Resolved: #305

[Feat] #305 - 대기방, 습관방 더보기(방 삭제, 방 나가기) 구현

---

Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
Spark-iOS/Spark-iOS/Source/Classes/LeftButtonNavigaitonBar.swift
Spark-iOS/Spark-iOS/Source/Classes/LeftRightButtonsNavigationBar.swift
Spark-iOS/Spark-iOS/Source/Classes/SparkActionSheet.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift

⛳️ **작업한 브랜치**
- feature/#312
👷 **작업한 내용**
인증사진 모아보기 대표이미지 변경 뷰 구현
만들어놨던 storageMoreVC를 재사용했습니다!
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/77208067/155966474-1ba5857c-f59e-4909-8256-c27e04649965.mp4" width ="250">|
- Resolved: #312

[Feat] #312 - 인증사진 모아보기 대표이미지 변경 뷰 구현

---

Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

⛳️ **작업한 브랜치**
- feature/#205
👷 **작업한 내용**
- 습관방 더보기 구현했습니당
- 물론 수빈선배가 방나가기 해주시고 
- 목표 수정뷰 연결했습니당
|기능|스크린샷|
|:--:|:--:|
|목표수정|<img src = "https://user-images.githubusercontent.com/69136340/156188498-fd564c69-1aac-4337-9c75-552f17e7006d.MP4" width ="250">|
- Resolved: #205

[Feat] #205 - 습관방 더보기 구현

---

Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Room/WaitingRoom.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

⛳️ **작업한 브랜치**
- feature/#334
👷 **작업한 내용**
리사이징된 이미지 반영
- 피드
- 대기방
- 피드 외의 프로필 사진 부분에서는 medium을 쓰고 싶어서 썼는데... small로 사용해야될까요....?
- 불필요한 옵셔널 제거했습니다
|기능|스크린샷|
|:--:|:--:|
| 피드 |<img src = "https://user-images.githubusercontent.com/81167570/156345840-d5ffdb4e-21b2-4c90-b93b-eced88c73884.PNG" width ="250">|
| 대기방 |<img src = "https://user-images.githubusercontent.com/81167570/156345754-6781bb7f-4f3f-445c-92c8-fd8eb26d48cc.PNG" width ="250">|
- Resolved: #334

[Refactor] #334 - 리사이징된 이미지 반영

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomLeaveVC.swift

⛳️ **작업한 브랜치**
- feature/#339
👷 **작업한 내용**
다이얼로그 멘트 수정 반영
- 습관방 나가기
- 방 만들기 
- 쉴래요
|기능|스크린샷|
|:--:|:--:|
- Resolved: #339

[Chore] #339 - 다이얼로그 멘트 수정 반영

---

Spark-iOS/Spark-iOS/Source/Cells/Storage/DoingStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Storage/DoneStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Storage/FailStorageCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Spark-iOS/Spark-iOS/Source/Views/CompleteAuth/ViewForRender.swift

⛳️ **작업한 브랜치**
- feature/#333
👷 **작업한 내용**
리사이징된 이미지 받아오도록 수정
인스타공유 프로필 이미지 컨텐트모드 적용
- Resolved: #333

[Feat] #333 - 리사이징된 이미지 받아오도록 수정

---

Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedAPI.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift

⛳️ **작업한 브랜치**
- feature/#353
👷 **작업한 내용**
피드 신고 서버 연결
제 맘대로... 이미 신고된 피드를 신고할 경우 토스트 메세지 추가했습니다...
아니 없으니까 뭔가 뒤로 돌아가지도 않고 머 어색하고 그러더라구요!
몰래 한거니까 우리끼리의 비밀로 하십시다 예? 이거 맞나? 아님 말씀드리고...
|기능|스크린샷|
|:--:|:--:|
|  이미 신고 함   |<img src = "https://user-images.githubusercontent.com/81167570/157084366-7961b873-7d42-4b70-9084-b5c2144fa7a6.PNG" width ="250">|
|  신고 함   |<img src = "https://user-images.githubusercontent.com/81167570/157084456-d10ffa59-b12e-4f02-ab00-2fdc2fefc98b.PNG" width ="250">|
- Resolved: #353

[Feat] #353 - 피드 신고 서버 연결

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#357
👷 **작업한 내용**
*주요 작업 내용*
- BottomButton 컴포넌트 분리
- 커스텀 네비게이션바 구현
- 커스텀 액션시트 구현
- Issue, Pull requests 템플릿 변경
#294 #304 #308 #309 #311 #313 #316 #318 #320 #321 #322 #330 #338 #341 #344 #346 #347 #349 #354 #355 #356
#285 #323 #325 #335
#297 #299 
#289 
#291
#303 #331 #340
- Resolved: #357

[Chore] #357 - 빌드 버전 변경(10)

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift

⛳️ **작업한 브랜치**
- feature/#360
👷 **작업한 내용**
- 로그아웃 다이얼로그가 삭제되었습니당
- Resolved: #360

[Fix] #360 - 로그아웃 다이얼로그 삭제

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift

⛳️ **작업한 브랜치**
- feature/#352
👷 **작업한 내용**
- 문의하기를 통한 인앱 메일 보내기를 구현했습니다.
- teamsparker66 지메일에 전달되는 것까지 확인했습니다.
- 메일 계정이 연동되어있지 않은경우 설정에서 설정해달라는 alert 창도 추가해주었습니다.
- 문구는 변동 예정에 있습니다. 기능을 붙여두고 추후에 변동되면 수정해두겠습니당
|기능|스크린샷|
|:--:|:--:|
|메일 전송|<img src = "https://user-images.githubusercontent.com/69136340/157422121-164c88e3-fa86-4a35-aa9e-6e72fd2e9602.MP4" width ="250">|
|메일 계정 연동실패|<img src = "https://user-images.githubusercontent.com/69136340/157420914-747f34f7-ea5a-41fc-afaa-eecd47197675.mp4" width ="250">|
- Resolved: #352

[Feat] #352 - 마이페이지 고객센터-문의하기 구현

---

Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift

분기별 인증완료 팝업 구현
⛳️ **작업한 브랜치**
- feature/#367
👷 **작업한 내용**
- sparkFlake 클래스에 메서드 추가
- 서버에서 인증 완료시 보내주는 day를 leftday로 가공하여 사용
있겠는 걸요 -> 있겠는걸요로 수정해 놓았습니다!
|기능|스크린샷|
|:--:|:--:|
|사진|<img src = "https://user-images.githubusercontent.com/77208067/157802716-d0707dfa-e2c2-4e84-89cf-1f0eb1690137.jpeg" width ="250">|
|사진|<img src = "https://user-images.githubusercontent.com/77208067/157802720-32a61859-682a-4803-b0b7-3ef5a7a241e9.jpeg" width ="250">|
- Resolved: #367

[Feat] #367 - 분기별 인증완료 팝업 구현

---

Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Feed/Feed.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift

⛳️ **작업한 브랜치**
- feature/#362
👷 **작업한 내용**
피드 내 인증인 경우 더보기 버튼 hidden 처리
|기능|스크린샷|
|:--:|:--:|
|  내 인증  |<img src = "https://user-images.githubusercontent.com/81167570/157834769-d734b12a-5454-4979-afc5-7025458565f6.jpeg" width ="250">|
- Resolved: #362

[Feat] #362 - 피드 내 인증인 경우 더보기 버튼 hidden 처리

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/SparkNotificationService/Info.plist
Spark-iOS/SparkNotificationService/NotificationService.swift

⛳️ **작업한 브랜치**
- feature/#398
👷 **작업한 내용**
**payload 의 body 값인 URL 을 통해서 사진을 다운로드 받아 notification 에 보여주었습니다.**
- `Notification Service Extension` 추가
- `Notification Service Extension` 에서 페이로드 컨텐츠 수정
> 다음과 같이 서버에서 payload 를 보내줍니다.
```swift
apns: {
payload: {
aps: {
alert: {
'title': 'certification title text',
'body': 'certification body text',
},
'category': 'certification',  // notification identifier.
'thread-id': 'certification', // notification grouping 을 위해 필요한 key.
'mutable-content': 1,         // notification service extension 사용하려면 1.
},
},
fcm_options: {
image: 'https://www.imageUrl',
},
}
```
> 서버와 회의했던 노션: https://jealous-supernova-274.notion.site/03888714ff32415cbca0b2823d8fe57e
> APNs payload 를 정리한 블로그: https://gyuios.tistory.com/151?category=1004599
- 빌드시에 다음과 같이 타겟으로 변경 후 …

[Feat] #398 - APNs notification service extension 사용해서 커스텀하기

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#408
👷 **작업한 내용**
#363 #366 #370 #373 #374 #377 #378 #380 #381 #387 #393 #395 #397 #399 #403 #405 #406 #407
#361 #365 #385
#391 
#369
- Resolved: #408

[Chore] #408 - 빌드 버전 변경(11)

---

Spark-iOS/Spark-iOS/Source/Extensions/UIFont+.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift

⛳️ **작업한 브랜치**
- feature/#376
👷 **작업한 내용**
알림뷰 문제 해결
- 엠티뷰 제대로 적용
- 번갈아 스크롤 할 경우 scrollToTop 펑 터지는 문제 해결
- 엠티뷰 처리가 제대로 안되어있어서 함수 분리하고 서버 통신 후 처리하도록 했습니다.
- scrollToTop은 collectionView가 보이는 경우에만 하도록 해서 터지는 문제 막았습니다.
|기능|스크린샷|
|:--:|:--:|
- Resolved: #376 #413

[Fix] #376 - 알림뷰 문제 해결

---

Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomGuideCVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomGuideVC.swift

⛳️ **작업한 브랜치**
- feature/#422
👷 **작업한 내용**
습관방 이용가이드 스크롤 영역 height 조정
- 스크롤 영역 이렇게 잡았습니다
- Resolved: #422

[Design] #422 - 습관방 이용가이드 스크롤 영역 height 조정

---

Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

⛳️ **작업한 브랜치**
- feature/#425
👷 **작업한 내용**
습관 시작 후 습관방 이동 플로우 적용
- noti로 적용했습니다
- WaitingVC에서 noti가 두 종류가 생겨서 기존에 있던 `postNotification` 이름 바꿨습니다
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/81167570/159633581-9eff5b6b-5d52-4627-8c86-8c3b9e16c84d.mov" width ="250">|
- Resolved: #425

[Feat] #425 - 습관 시작 후 습관방 이동 플로우 적용

---

Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedHeaderView.swift
Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
Spark-iOS/Spark-iOS/Source/Cells/Mypage/NotificationTVC.swift
Spark-iOS/Spark-iOS/Source/Extensions/UILabel+.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift

⛳️ **작업한 브랜치**
- feature/#431
👷 **작업한 내용**
- 임포트한 프레임워크를 수정해주었습니다.
- UILabel 을 extension 해서 사용했습니다!
- 라벨의 tap gesture recognizer 로 터치된 CGPoint 가 전달됐을 때, 특정 문자열의 CGRect 가 전달된 탭 포인트를 포함하면 특정 문자열을 탭했다고 여겨 노션으로 연결해주었습니당
- 참고한 포스트
> https://team.postype.com/post/9439360
|기능|스크린샷|
|:--:|:--:|
|로그인뷰|<img src = "https://user-images.githubusercontent.com/69136340/160537679-45ca547d-7a77-4671-a263-7e597205ee20.mp4" width ="250">|
- Resolved: #431

[Feat] #431 - 로그인 이용약관, 개인정보 처리 방침 노션 연결

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#442
👷 **작업한 내용**
- 홈 성공/실패 로티 추가
- 마이페이지 알림, 로그아웃, 회원탈퇴, 노션 연결
- 습관 시작 후 습관방으로 가는 플로우 구현 
#418 #420 #425 #426 #430 #431 #437
#413 #414 #424 #433
#410 #412 #417 #422
- Resolved: #442

[Chore] #442 - 빌드버전 변경 및 최소 지원 버전 변경

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/NotificationVC.swift

⛳️ **작업한 브랜치**
- feature/#457
👷 **작업한 내용**
- table view style 을 grouped 로 변경
- footer 높이 설정
- background color 설정
|기능|스크린샷|
|:--:|:--:|
|plain 일때|<img src = "https://user-images.githubusercontent.com/69136340/160989340-789ae426-db92-4c5e-9ebb-d463dc143a56.mp4" width ="250">|
|grouped 일때|<img src = "https://user-images.githubusercontent.com/69136340/160989346-79592c51-0e10-49b4-8db5-8d41b77916dd.mp4" width ="250">|
- Resolved: #457

[Fix] #457 - 마이페이지, 알림뷰에서 스크롤시 헤더 고정시키지 않기

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift

⛳️ **작업한 브랜치**
- feature/#453
👷 **작업한 내용**
습관방 인증방식 선택 시 번갈아 활성화되는 문제 해결
더 깔꼼하게 짤 수 있을 것 같긴 한데.. 머.. 멀라.. 😡
|기능|스크린샷|
|:--:|:--:|
- Resolved: #453

[Fix] #453 - 습관방 인증방식 선택 시 번갈아 활성화되는 문제 해결

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

⛳️ **작업한 브랜치**
- feature/#455
👷 **작업한 내용**
- Base View Controller 를 만들어서 모든 view controller 에 적용해야하는데 그러기엔 매 view controller 마다 공통적으로 들어가는 메서드나 프로퍼티가 없어서 오히려 오버헤드가 크다고 판단했습니다.
|기능|스크린샷|
|:--:|:--:|
- Resolved: #455

[Feat] #455 - 스와이프 팝 제스처 extension 정리

---

Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

⛳️ **작업한 브랜치**
- feature/#445
👷 **작업한 내용**
습관방 더보기 순서 변경
|기능|스크린샷|
|:--:|:--:|
- Resolved: #445

[Fix] #445 - 습관방 더보기 순서 변경

---

Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

⛳️ **작업한 브랜치**
- feature/#474
👷 **작업한 내용**
- 습관방에서 시간과 목표가 설정되어있지 않다면
```swift
아직 구체적인 계획이 없어요.
나만의 시간과 목표를 작성해 보세요!
```
와 같이 문구 변경
|기능|스크린샷|
|:--:|:--:|
|습관방문구|<img src = "https://user-images.githubusercontent.com/69136340/161476385-5befca01-fd31-4c95-820e-064e94d4a7e8.png" width ="250">|
- Resolved: #474

[Fix] #474 - 습관방 시간,목표 문구 변경

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift

⛳️ **작업한 브랜치**
- feature/#494
👷 **작업한 내용**
습관 인증에서 타이머가 작동 중일때는 화면이 꺼지지 않도록 했습니다.
```
// 화면 꺼짐 방지
UIApplication.shared.isIdleTimerDisabled = true
// 화면 꺼짐 방지 해제
UIApplication.shared.isIdleTimerDisabled = false
```
일단 구현해뒀는데, 기획 측에게 땅땅땅 받으면 머지할게욥
|기능|스크린샷|
|:--:|:--:|
- Resolved: #494

[Fix] #494 - 타이머 작동 중 화면 꺼짐 방지

---

Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

⛳️ **작업한 브랜치**
- feature/#499
👷 **작업한 내용**
나의 목표 수정 -> 나의 목표 관리
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/81167570/162237316-706e0d14-8d8b-4811-b5df-247229585612.jpeg" width ="250">|
- Resolved: #499

[Fix] #499 - 나의 목표 수정 문구 변경

---

Spark-iOS/Spark-iOS/Source/Cells/Mypage/NotificationTVC.swift

⛳️ **작업한 브랜치**
- feature/#493
👷 **작업한 내용**
- 알림뷰에서 리마인드 문구 변경(21:00 -> 22:00)
- 알림뷰 스위치 색상 변경(spark pink red)
|기능|스크린샷|
|:--:|:--:|
|알림뷰|<img src = "https://user-images.githubusercontent.com/69136340/162234904-ff9f25c3-7729-4d39-bf2e-f4f10d3b52c6.png" width ="250">|
- Resolved: #493

[Fix] #493 - 알림뷰에서 리마인드 문구 변경 및 스위치 색상 변경

---

Spark-iOS/Spark-iOS/Source/Extensions/UIImageView+.swift

⛳️ **작업한 브랜치**
- feature/#498
👷 **작업한 내용**
-  kingfisher 720*720 코드 수정
- 이미지 리사이징 적용시 720 가 원본이되니까 720 사이즈가 필요할때 원본 URL 을 주면되서 코드를 수정했습니다.
- Resolved: #498

[Fix] #498 - kingfisher 720*720 코드 수정

---

Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift

⛳️ **작업한 브랜치**
- feature/#497
👷 **작업한 내용**
- 플로팅 버튼 폰트 변경
- 플로팅 버튼 크기 수정(본 버튼, 하위 버튼)
|기능|스크린샷|
|:--:|:--:|
|플로팅 버튼|<img src = "https://user-images.githubusercontent.com/69136340/162238701-e9512502-d41a-402c-8210-5298fb668162.jpeg" width ="250">|
- Resolved: #497

[Fix] #497 - 플로팅버튼 폰트, 크기 수정

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#509
👷 **작업한 내용**
- [마이페이지] 회원 탈퇴 구현
- [인증하기] 스톱워치 구현
- [홈] 엠티뷰 수정
- [보관함] D-Day 테두리 추가 및 레이아웃 기기대응
- [대기방/습관방] 시간, 목표 멘트 수정
- [스파크 보내기] 이모지 키보드 레이아웃 대응
- [알림] 리마인드 문구 수정 및 스위치 색상 변경
- [홈] 플로팅 버튼 폰트, 크기 수정
- [습관방] "나의 목표 관리" 문구 수정
- [회원가입] 프로필 삭제시 액션시트 닫기
- #468
- #472 
- #475 
- #477 
- #478
- #485 
- #486
- #487 
- #490
- #496 
- #501
- #502 
- #503
- #504
- #507
- #482
- #505
- Resolved: #509

[Chore] #509 - 빌드 버전 변경(14)

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#530
👷 **작업한 내용**
- [홈] 알림 빨간불 구현
- 플로팅 버튼 화면전환 중에는 터치되지 않도록 수정
- 특정 뷰에서 15자 제한이 10자 제한되는 버그 수정
- [인증하기]에서 다시 [스톱워치] 로 돌아와도 백그라운드에서 기능하도록 구현
- [습관방] 일러스트 추가
- [스파크 보내기] 이모지 키보드 대응 버그 수정
- [인증 완료] 팝업 문구 수정
- [회원 탈퇴] 체크박스 선택시 텍스트 컬러 변경
- 유니버셜 링크 구현
- #512
- #514
- #518
- #527
- #515 
- #517
- #520 
- #522 
- #524  
- #529
- #519
- Resolved: #530

[Chore] #530 - 빌드 버전 변경(15)

---

Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift

⛳️ **작업한 브랜치**
- feature/#536
👷 **작업한 내용**
- 대기방에서 홈을 갈때를 포함해서 viewWillAppear 에서 네비바를 초기화해줍니당 
- 원래 이렇게 의논했는데 제가 반영은 안해뒀다구여어,,, ㅎㅎ
- Resolved: #536

[Fix] #536 - 홈 로딩 끝나고 알림 빨간불 반영

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#541
👷 **작업한 내용**
○ 네트워크 손실 시 알림창 구현
○ 강제 업데이트
○ [방 생성] 으로 뒤로가기를 통해 돌아왔을 때 숫자 카운트 변하지 않는 버그 해결
○ 프로필 설정 및 수정뷰 이모지 키보드 대응
- #532
- #533
- #538
- #535
- #537
- Resolved: #541

[Chore] #541 - 빌드 버전 변경(16)

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift

⛳️ **작업한 브랜치**
- feature/#550
👷 **작업한 내용**
막았습니당
`navigationController?.interactivePopGestureRecognizer?.isEnabled = false`
|기능|스크린샷|
|:--:|:--:|
- Resolved: #550

[Bug] #550 - 습관방 생성 확인 뷰에서 swipe back gesture 막기

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS.xcworkspace/contents.xcworkspacedata
Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/Dialogue.storyboard
Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/SingleResponseDialogue.storyboard
Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/SingleResponseDialogueVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift

⛳️ **작업한 브랜치**
- feature/#553
👷 **작업한 내용**
- 다음과 같이 무조건 다이얼로그가 등장하도록 주석 처리하고 결과를 확인했습니다.
```swift
DispatchQueue.main.asyncAfter(deadline: DispatchTime.now() + 1) {
//            if self.checkUpdateAvailable() {
self.presentToForceUpdateDialougeVC()
//            }
}
```
|기능|스크린샷|
|:--:|:--:|
|강제업데이트|<img src = "https://user-images.githubusercontent.com/69136340/164768129-44250515-4a2f-4cf8-b74b-dd679a5a3f30.MP4" width ="250">|
- Resolved: #553

[Fix] #553 - 강제 업데이트 다이얼로그 구현

---

Spark-iOS/Spark-iOS/Resource/Constants/URL.swift

⛳️ **작업한 브랜치**
- feature/#556
👷 **작업한 내용**
- 노션을 정리하시다가 링크 주소가 변경되었다고 합니당 수정하겠습니다.
- 퀵헬프 주석 추가
- [로그인] 이용약관, 개인정보처리방침 URL 변경
- [마이페이지] 약관 및 정책, 오픈소스 라이브러리 URL 변경
- 유지보수 깔끔하고요... 👍
- Resolved: #556

[Fix] #556 - 노션 주소가 변경되어 URL 수정

---

Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift

⛳️ **작업한 브랜치**
- feature/#569
👷 **작업한 내용**
- 푸시알림을 제외한 제 담당 부분 모두 코드 추가했습니다.
- SendSparkButton 이 변수를 모두 옵셔널로 갖고 있는데 이 부분이 불필요 할거 같아서 이니셜라이저를 다시금 설정해서 리펙토링을 진행할 예정입니당.
- Resolved: #569

[Feat] #569 - 트래킹 코드 추가

---

Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Feed/FeedReportVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift

⛳️ **작업한 브랜치**
- feature/#548
👷 **작업한 내용**
- 기존의 코드를 변경했습니당. 구글링으로 얻은 정보와 개발자문서를 비교해서 코딩했었는데.. 어울리지 않는 메서드를 사용했던 것 같아요!
- 구글링을 통해서 확실한 코드를 가져왔습니당
- 변경된 코드는 gesture recognizer 가 터치 해석을 시작해야하는지 delegate 에게 묻는 코드입니다. 
- 전에 소개했던 아래의 코드는 scrollview 에서 gesture 를 감지하고 싶을 떄와 같이 겹칠때 true 로 설정해서 인식하는 코드였었어요. 
```swift
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
return navigationController?.viewControllers.count ?? 0 > 1
}
```
- 정확히는 왜 이게 되지 않는지는 잘 모르겠습니당 ㅜ 모든 구글링 결과와 제 여러가지 delegate 메서드를 사용해본 결과 변경된 코드가 정상 실행되더라구요. 
- Resolved: #548

[Bug] #548 - 방 생성 뷰에서 스와이프 pop 제스처하면 화면 멈춤 해결

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#585
👷 **작업한 내용**
- 빌드 버전 변경(16->17)
- 리프레쉬할 때 강제 종료 및 엠티뷰 등장 버그 해결
- [방 생성] 시 스와이프 제스처 버그 해결
- 방 삭제 시 개설자 토스트 메시지 분기처리
- [강제 업데이트 다이얼로그] 구현
- 스파크 노션 주소 변경 반영
- [마이페이지] 프로필 보이지 않는 버그 해결
- 트래킹 코드 구현
- 이모지 키보드 대응
- 햅틱 추가
- [보관함] 대표 이미지 변경 버그 해결
- 앱 언어 Korea 변경(붙여넣기, 카메라 등 한글 지원)
- #555
- #564
- #568 
- #570
- #573
- #576
- #581
- #584
- #545
- #552
- #554
- #557 
- #558
- #561
- #565
- #574
- #578
- #580
- #551
- #583
- Resolved: #585

[Chore] #585 - 빌드 버전 변경(17)

---

Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeActiveCVC.swift

⛳️ **작업한 브랜치**
- feature/#이슈번호
👷 **작업한 내용**
알림뷰 contentImageView radius 수정
|기능|스크린샷|
|:--:|:--:|
|수정 전|<img src = "https://user-images.githubusercontent.com/81167570/166420860-35088b29-e4b1-4060-8fc1-f087b2fb4a2a.jpeg" width ="250">|
|수정 후|<img src = "https://user-images.githubusercontent.com/81167570/166420923-d4a2d03b-f1c2-4c42-8042-af23ae3d075c.jpg" width ="250">|
- Resolved: #591

[Fix] #591 - 알림뷰 contentImageView radius 수정

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#597
👷 **작업한 내용**
- 카메라, 앨범 권한 문구를 수정했습니다.
`프로필 사진 설정 및 변경, 습관 인증을 위해 카메라/앨범 권한을 허락해 주세요.`
|기능|스크린샷|
|:--:|:--:|
|카메라 권한|<img src = "https://user-images.githubusercontent.com/69136340/166713606-438483ac-e299-4186-9b35-b0433c620242.png" width ="250">|
- Resolved: #597

[Reject] #597 - 카메라, 앨범 권한 문구 수정 및 빌드 업데이트(21)

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#610
👷 **작업한 내용**
- #602
- #571
- Resolved: #610

[Chore] #610 - 버전 및 빌드 업데이트(1.0.1)

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift

⛳️ **작업한 브랜치**
- feature/#613
👷 **작업한 내용**
- 릴리즈한 후 develop 브랜치로 머지했습니다.
- Resolved: #613

[Chore] #613 - release-1.0.1 -> develop 머지

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#633
- #619
- #621 
- #624 
- #632
- #623 
- #627 
- #628 
- #630 
- Resolved: #633

[Chore] #633 - 버전 및 빌드 업데이트(1.0.2)

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#635
👷 **작업한 내용**
- 릴리즈를 위해 머지하겠습니다.
- Resolved: #635

[Chore] #635 - release-1.0.2 -> develop 머지

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj

⛳️ **작업한 브랜치**
- feature/#643
👷 **작업한 내용**
- 빌드 및 버전 업데이트 후, 릴리즈 브랜치를 만들었습니다. 
- 이번 푸시알림 업데이트 및 추가적인 작업은 여기서 진행하면 될 것 같습니다.
- 앱 아이콘 단일화 작업을 할 예정이고, 10월 1일 릴리즈 예정입니다. 그 전까지의 작업이 있다면 여기서 해주세용
- Resolved: #643

[Chore] #643 - 버전 및 빌드 업데이트(1.0.3)

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Source/Cells/LifeTimeLine/LifeTimeLineCVC.swift
Spark-iOS/Spark-iOS/Source/NetworkModels/Room/TimeLine.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/LifeTimeLine/LifeTimeLineVC.swift

⛳️ **작업한 브랜치**
- feature/#664
👷 **작업한 내용**
- release 1.0.4 를 준비하겠습니당
- Resolved: #664

[Chore] #664 - release-1.0.4 브랜치로 develop 브랜치 merge

---

Spark-iOS/Podfile.lock
Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

⛳️ **작업한 브랜치**
- feature/#666
👷 **작업한 내용**
- 생명 타임라인 트래킹 추가
- 생명 타임라인 탭할 경우 습관방 new 빨콩 히든
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/81167570/194810769-548cbeda-8ecb-4573-92f6-ffb5193d681b.mov" width ="250">|
- Resolved: #666

[Feat] #666 - 생명 타임라인 트래킹 추가

---

Spark-iOS/Podfile.lock
Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/Spark-iOS/Resource/Assets.xcassets/sparkFlakeSparkFlake1.imageset/Contents.json
Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/UpgradeFlakeDialogue.storyboard
Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/UpgradeFlakeCVC.swift
Spark-iOS/Spark-iOS/Source/Classes/UpgradeFlakeCarouselLayout.swift
Spark-iOS/Spark-iOS/Source/Extensions/UIView+.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/UpgradeFlakeDialogueVC.swift
Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift

⛳️ **작업한 브랜치**
- feature/#668
👷 **작업한 내용**
- `UpgradeFlaekDialouge` : 불꽃 결정 로드맵 뷰를 스토리보드로 구현하였습니다.
- 중앙 flake 의 경우 120 사이즈로 통일하고, 가로 화면에 따라서 line spacing(collectionView.frame.width / 10)을 주었습니다.
- 준호가 이전에 보관함 짤 때 사용한 케러셀 레이아웃을 조금 수정했습니다.(참고 - https://lsh424.tistory.com/54)
- 그라데이션을 재활용할 수 있게 수정했습니다.
- UI components 이름을(levelTitle, subtitle)수정하였습니다.
- _**페이징 간격이 좁아서 페이징 느낌이 잘 안들더라구요 그래서 햅틱을 추가해서 다이얼의 느낌을 내보았습니다! 훨씬 괜찮은거 같아서 한번 봐주십사합니다!**_
- https://stackoverflow.com/questions/51254261/when-are-subviews-completely-correctly-laid-out
- https://medium.com/@marcosantadev/calayer-and-auto-layout-with-swift-21b2d2b8b9d1
위의 참고자료를 통해서 코드베이스로 작성할 때 layer 의 frame 을 정해주는 시점을 찾고자.. 했는데 그러지 못해서 스토리보드로 작성하였습니당 다들 저렇게 하면 된다던디이..ㅜ
커밋 기록에서.. 코드베이스로 작성한 히스토리가 있으니.. 혹시나 아시는 분은 코드 한번 봐주셔도 감사하겠습니다아~ …

[Feat] #668 - 불꽃 결정 로드맵 collection view 페이징 구현

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/fastlane/Fastfile

⛳️ **작업한 브랜치**
- feature/#684
👷 **작업한 내용**
- app extension 버전 1.1.0 으로 통일.
- release lane 에서 build number 증가시키는 명령어 추가.
- 앱 프로젝트에서 다음 경고를 보고 notification service 버전 업데이트했습니다.
- Resolved: #684

[Chore] #684 - app extension 의 버전 업데이트 및 fastlaen 수정

---

Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
Spark-iOS/fastlane/Fastfile

⛳️ **작업한 브랜치**
- feature/#686
👷 **작업한 내용**
__Originally posted by @hyun99999 in https://github.com/TeamSparker/Spark-iOS/pull/677#discussion_r1014549098__
이 부분에서 release lane 의 build scheme 가 변경되었고, 그래서 이번 배포에서 테스트 서버로 배포되었습니다.
처음 자동 배포다 보니 거듭 확인했어야 했는데 죄송합니다🙇🏻‍♂️
아래 git flow 참고해서 hotfix 로 적용하고 디벨롭과 메인에 머지하겠습니다.
> https://techblog.woowahan.com/2553/
- Resolved: #686

[Chore] #686 - fastlane release lane 의 build scheme 수정
