TeamSparker/Spark-iOS

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Feed.storyboard
- Spark-iOS/Spark-iOS/Source/Cells/FeedCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/FeedHeaderView.swift
- Spark-iOS/Spark-iOS/Source/Extensions/UIView+Extension.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
🌱 작업한 브랜치
- feature/#16
🌱 작업한 내용
- FeedHeaderVIew 레이아웃
- FeedCVC 레이아웃
- FeedVC 레이아웃
- 더미데이터 추가 + 무한스크롤 구현
- UIView+Extension 추가
이게 최선의 코드인지는 잘 모르겠습니다.. 그치만 급한 것 같고.. 정상적으로 작동하며 또 다른 일들이 기다리고 있기 때문에 일단 올립니다!
무한스크롤 구현하는 방식을 전에 연습했던 것과 현규선배가 알려준 방식 두개 다 해봤는데,
현규선배가 알려준 방식에서 isInfiniteScroll 요 친구를 서버 통신할때 true 처리는 것 같은데 확실히 모르겠어서 일단 네.. 둘 다 살려뒀습니다.
|기능|스크린샷|
|:--:|:--:|
| 피드뷰 | ![ezgif com-gif-maker (29)](https://user-images.githubusercontent.com/81167570/149192342-1e3a70bf-85aa-4123-b580-95e4974c824c.gif) |
- Resolved: #16
> [Feat] #16 - 피드뷰 레이아웃 구현

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
- Spark-iOS/Spark-iOS/Resource/Constants/UserDefaults.swift
- Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
- Spark-iOS/Spark-iOS/Resource/Info.plist
- Spark-iOS/Spark-iOS/Resource/Storyboards/Base.lproj/LaunchScreen.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/Login/Login.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/Splash/Splash.storyboard
- Spark-iOS/Spark-iOS/Source/AppDelegate.swift
- Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
- Spark-iOS/Spark-iOS/Spark-iOS.entitlements
🌱 작업한 브랜치
- feature/#23
🌱 작업한 내용
- 스플래시 화면 구현
- 스플래시뷰에서 온보딩, 메인, 로그인 화면전환 분기 처리
- 로그인뷰 구현
- 로그인뷰 카카오, 애플 로그인 구현
- appdelegate 에서 카카오와 애플의 로그인 유효성 여부를 판단하고 splash 뷰에서 appdelegate 의 변수를 가져와서 화면전환하는 용도입니다.
- splash 에서 viewWillAppear 로 화면전환을 하는 이유는 viewDidLoad 에서 진행하면 화면이 다그려지지 않았는데 화면전환한다고 에러를 뱉습니당! 그래서 1초를 줘서 이쁜 스플래쉬를 보여주고~ 화면전환~
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src="https://user-images.githubusercontent.com/69136340/149206865-12d83259-2120-41b0-829c-3a9b41c6b18c.jpeg" width ="250">|
- Resolved: #23
> [Feat] #23 - 스플래시, 로그인 뷰 구현

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsKey.swift
- Spark-iOS/Spark-iOS/Source/AppDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Login/LoginVC.swift
🌱 작업한 브랜치
- feature/#28
🌱 작업한 내용
- userID 와 accessToken Userdefaults 로 저장 후 사용
- Resolved: #28
> [Feat] #28 - 유저아이디, 엑세스토큰 UserDefaults 으로 저장 구현

- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
🌱 작업한 브랜치
- feature/#58
🌱 작업한 내용
- 플로팅 버튼 화면전환 기능 구현 
- 코드 다시 입력하기 기능 구현
- 플로팅 버튼 화면전환은 코드로 참여 부분만 구현했습니다.
- Resolved: #58
> [Feat] #58 - 플로팅 버튼 터치 시 화면전환 및 코드 다시 입력하기 기능 구현

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
- Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
- Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/Dialogue.storyboard
- Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
🌱 작업한 브랜치
- feature/#113
🌱 작업한 내용
- 총 4개의 케이스에 대한 다이얼로그 구현
- 회원가입 나가기
- 인증 나가기
- 타이머 초기화
- 타이머 나가기
- dialogue를 호출할 때 dialogueType 프로퍼티를 지정해주시면 됩니다.
- resetOrExitAction에 원하는 액션을 넣어주시면 됩니다.
|기능|스크린샷|
|:--:|:--:|
|디자인|![Simulator Screen Recording - iPhone 11 Pro - 2022-01-19 at 04 12 48](https://user-images.githubusercontent.com/77208067/150003229-6e7be1fb-deee-4448-8188-83c9bb907c8e.gif)|
- Resolved: #113
> [Feat] #113 - 케이스별 dialogue 구현

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
- Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
- Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#63
🌱 작업한 내용
-  애니메이션 회전 방향 변경
-  함께하는 스파커 append 문제 해결
-  se2
-  13 mini
-  13 pro
탭바랑 플로팅 버튼이 남아있어서 그 부분이 없어진다는 가정하에 레이아웃 수정했슴다
|기능|스크린샷|
|:--:|:--:|
| 생략 | 생략 |
- Resolved: #63
> [Feat] #63 - 대기방 기기대응 및 수정

- Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
- Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/CodeJoin.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/Create/CreateRoom.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/CompleteAuth.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
- Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
- Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
🌱 작업한 브랜치
- feature/#130
🌱 작업한 내용
- 보관함 베지어패스 수정
- 기기대응 완료한 뷰
- Dialogue
- SendSpark
- CompleteAuth
- HabitAuth
- JoinCheck
- CodeJoin
- StorageMore
- Storage
- 현규선배 함수에서 객체를 리턴해서 애니메이션 지워주고 만들어주는 방법 잘 배웠습니다
- 하지만 태그 처음써서 문제 해결한게 뿌듯해서 태그로 만든 코드로 푸쉬해요! ㅎㅎ
- authUpload 제외하고 제가 맡은 뷰 기기대응 완료입니다.
- 보관함 뷰 무한스크롤은 일단 막아뒀습니다.
- Resolved: #130
> [Feat] 13프로, 13미니, SE2 기기대응

- Spark-iOS/Spark-iOS/Source/Extensions/UINavigationController+.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#140
🌱 작업한 내용
- 탭바를 네비게이션 컨트롤러에 얹어서 스플래시에서 화면전환
- 피드에서는 네비바 안보임
- 홈에서는 네비바 보임. 타이틀없음
- 보관함에서는 네비바 안보임.
- 보관함 인증사진 모아보기에서는 네비바 보임.
- Resolved: #140
> [Fix] #140 - 탭바에서 네비게이션 바 QA

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Source/AppDelegate.swift
- Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/habitRoomMemberCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/Home/HomeWaitingCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
- Spark-iOS/Spark-iOS/Source/Extensions/UIImage+.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#154
- feature/#155
🌱 작업한 내용
- 습관방 만들기 화면전환
- 각종 코드 디테일 수정
- 인증사진 모아보기 뷰 분기처리
- 쉴래요 횟수에 따른 버튼 비활성화
- 이미지 피커 이미지 리사이징
- Resolved: #154 
- Resolved: #155 
- Resolved: #160
> [Feat] #155 - 습관방 만들기 화면전환 및 각종 코드 디테일 수정

- Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Feed.storyboard
- Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
🌱 작업한 브랜치
- feature/#159
🌱 작업한 내용
- feedImageView 이미지 레이아웃이 엉망인 상태 해결
- 인증하고 피드로 왔을 때 홈 탭했을 때 상세뷰 떠있는 문제 해결
- swipe back gesture 추가
스와이프에게 자유를.
|기능|스크린샷|
|:--:|:--:|
|생략|생략|
- Resolved: #159
> [Fix] #159 - 피드뷰 레이아웃 수정

- Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
- Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitAuth.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/HabitRoom/HabitRoom.storyboard
- Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/habitRoomMemberCVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
🌱 작업한 브랜치
- feature/#165
🌱 작업한 내용
- 습관방 멘트 수정
- 상태바 색 변경
- 고민중, 쉴래요 후 상태 스티커 반영
- 오늘의 인증 버튼 비활성화
- Resolved: #165
> [Fix] #165 - 습관방 멘트, 상태바, 상태 스티커 수정하기

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
🌱 작업한 브랜치
- feature/#192
🌱 작업한 내용
- 플로팅버튼 순서 수정
- 배경은 overlay -> defaultColor? -> alpha 값을 0.8로 하시면 됩니다
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #192
> [Chore] #192 - 플로팅버튼 순서 수정

- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#216
🌱 작업한 내용
- 대기방에서 dismiss 하는 분기처리
- FromWhereStatus 를 통해서 열거형으로 분기처리
```swift
/// 대기방을 접근하는 플로우를 알려주는 상태.
/// - fromHome : 홈에서 대기방 올 때.
/// - joinCode : 코드로 참여할 때.
/// - makeRoom : 방만들기로 대기방 올 때.
@frozen
enum FromWhereStatus {
case fromHome
case joinCode
case makeRoom
}
```
- 코드로 참여할 때 presenting view controller 를 로그로 찍어봤다.
> 지금은 스플래쉬 | 홈 | 코드입력팝업 | 코드참여 확인뷰 | 대기방
> 구조이고, 우리는 `presentingViewController?.presentingViewController` 이렇게 사용해서 `코드참여 확인뷰`를 닫고, `코드입력팝업`을 닫으려고 했어요! 하지만 그렇지를 못했져 이유를 알아봅시다..  
화면을 `dismiss` 로 걷어내는 객체는 해당 뷰컨이 아니라구 해여!  VC1이 VC2를 불렀다고 가정한다면, VC2가 화면에서 걷어지기 위해서는 VC1가 걷어줘야하는거죠!
어라..? 그러면  `self.dismiss` 가 아니라 `self.presentingViewController.dismiss` 를 써야하는거 아닌가요?
에 대한 답변으로 사용자의 관점에서 전혀 차이를 느낄 수 없다고 해여 
```swift
이 두 함수의 차이는 completion 함수 구현 시 발생한다. …
```
> [Fix] #216 - 대기방에서 뷰 dismiss 분기처리

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
🌱 작업한 브랜치
- feature/#209
🌱 작업한 내용
- 데이터를 append 하기 전에 `removeAll()`을 해줘서 값이 계속 늘어나는 문제 해결
- API 통신을 하기 전에 List에 있는 정보들을 모두 삭제해주는 방식으로 문제를 해결했습니다.
- 생각보다 간단하게 해결할 수 있는 문제였네염...
- 추가적인 방법으로 append를 할 때 List에 이미 값이 들어있는지 확인하고 없는 경우에만 append를 해줄 수 있을 것 같아요. 어떤 방법이 더 메모리 효율적일지는 모르겠서요! help...
- 다시 생각해보니까 바로 위 방법으로 하면 viewWillappear에서 API통신하는 의미가 없어지네요.. 머쓱..
- Resolved: #209
> [Fix] #209 - 데이터를 계속 append하여 셀이 증식하는 문제 해결

- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#214
🌱 작업한 내용
- 대기방에서 스와이프해서 pop 구현
현재 
`navigationController?.interactivePopGestureRecognizer?.delegate = nil`
코드를 통해서 네비바가 히든되어있을 때 스와이프 pop 을 구현하고 있는데요!
대기방의 경우는 뒤로가기 버튼이 있음에도 불구하고 위의 코드를 구현해야했어요!
> 네비바가 히든된 경우만 스와이프 pop 이 되지 않음
~그 이유가 현재 대기방은~
```swift
navigationController?.initWithTwoCustomButtonsTitle(navigationItem: self.navigationItem,
title: "\(title)",
tintColor: .sparkBlack,
backgroundColor: .sparkWhite,
reftButtonImage: UIImage(named: "icBackWhite"),
rightButtonImage: UIImage(),
reftButtonSelector: #selector(popToHomeVC),
rightButtonSelector: #selector(touchToMore))
```
~이런식으로 네비바의 backbutton 을 사용하지 않는 모양입니다! 그래서 스와이프 pop 을 필요로 하는거 같아요. 우리 플젝에서 나머지 백버튼은 모두 initBackButton 으로 구현되고 있습니다~
인줄 알았는데 타이머를 인증하는 부분에서는 스와이프가 되는 모양새더라구여. 네비바가 지금 어지러운 상태라서.. 탭바가 구현되고 …
> [Feat] #214 - 대기방에서 스와이프 pop

- Spark-iOS/Spark-iOS/Resource/Storyboards/StorageMore/StorageMore.storyboard
- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.xib
- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
🌱 작업한 브랜치
- feature/#221
🌱 작업한 내용
- 보관함 인증사진 모아보기에서 우측으로 정렬되는 이슈를 해결했다.
- MoreStroageCVC Xib 오토레이아웃을 수정했습니다
- 아래와 같이 셀사이즈를 기기가 바뀌어도 가로 사이 간격은 15을 유지하면서 187:160 비율을 지키도록 코드를 짜보았어요!
> 기존에 세로간격없이 꽉차있던것을  세로 간격은 16으로 추가했습니다! 이유는 준호한테 이런코드도 있다고 보여주고 싶었어용! 그때 말했던것처럼 간격역시 기기대응에서 비율로 가져갈건지 저처럼 16으로 가져갈건지에 대한 차이입니다!
```swift
// 양쪽 inset 40 + inter item spacing 15
let cellWidth: CGFloat = (collectionView.frame.width - 55) / 2
let cellHeight: CGFloat = (cellWidth * (187/160))
let cell = CGSize(width: cellWidth, height: cellHeight)
return cell
```
- 제플린
- MoreStorageCVC 수정
> superview 에 대해서 이미지뷰가 비율로 잡혀있었어요 아래 보는것처럼 = 표시가 세로에 있죵? 지워줬습니다 그리고 1대1이라서 괜찮지만 의도를 나타내기 위해서 상단과 좌우를 슈퍼뷰와 컨스트레인트를 잡아주었습니다.
- 문제해결
> 아래처럼 안전영역 밖으로 잡혀있었어요!
|기능|스크린샷|
|:--:|:--:|
|결과|<img …
> [Fix] #221 - 보관함 인증사진 모아보기 REST 이미지 우측 정렬되는 이슈

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
- Spark-iOS/Spark-iOS/Source/Cells/Waiting/WaitingFriendCVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#223
🌱 작업한 내용
- 코드로 방 참여 플로우에서 대기방에서 홈으로 이동시 플로팅 버튼 띄우기
> 해당 이슈 #223 참조
- 이외에도 WaitingVC 를 컨밴션에 맞춰서 조금 수정했어요!
원래는 마지막 클로저 매개변수는 이름을 적어주지 않는것이 컨밴션이어서 적어주지 않으니 
https://realm.github.io/SwiftLint/multiple_closures_with_trailing_closure.html 경고 등장!
후행클로저가 두개이상인 경우 매개변수명을 다 적어줘야한다고해서 변경해두었습니다.
```swift
private func refreshButtonAnimtation() {
UIView.animate(withDuration: 0.4,
delay: 0.1,
options: .curveEaseInOut,
animations: {
let rotate = CGAffineTransform(rotationAngle: -3.14)
self.refreshButton.transform = rotate
},
completion: { _ in
self.refreshButton.transform = .identity
})
}
```
- WaitingFriendCVC 접근제어자 설정 및 extensions 분리, identifier 제거 후 Const 로 관리
- WaitingVC 접근제어자 설정
- Xib 폴더 Cell 로 변경해서 코드베이스의 경우도 identifier 를 const 로 관리하도록 함
- 스위프트린트에 맞춰서 다중 후행클로저 수정
- 대기방 멤버 …
> [Fix] #223 - 대기방에서 홈으로 이동시 플로팅 버튼 띄우기

- Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/habitRoomMemberCVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
🌱 작업한 브랜치
- feature/#226
🌱 작업한 내용
- 다른 멤버들의 상태에 따른 분기처리에 이미지 설정 코드 추가
|기능|스크린샷|
|:--:|:--:|
|습관방 스티커|<img src="https://user-images.githubusercontent.com/69136340/151915607-bbc8113b-f01a-48fe-958e-a4d6c264a670.jpeg" width ="250">|
- Resolved: #226
> [Feat] #226 - 습관방에서 멤버 상태스티커 반영

- Spark-iOS/Spark-iOS/Resource/Constants/Cell.swift
- Spark-iOS/Spark-iOS/Source/Cells/Feed/FeedCVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
🌱 작업한 브랜치
- feature/#210
🌱 작업한 내용
- 피드 done 태그 찌그러지는 문제 수정
- 피드 좋아요 로티 함수 분리
- 피드 좋아요 문제 해결 못함..
좋아요 로티가 자기 멋대로 발동하고 있습니다..
어떤 경우 문제가 발생하는지 파악하려고 이것 저것 좋아요 누르다가 어떨 때 문제가 생기는지는 찾았는데, 근데 아직 머가 문제인지 정확하게는 모르겠습니다...
처음에는 cell reuse 문제인가 해서 prepareForReuse에 likeState = true 를 해줘보기도 했는데 이게 문제가 아닌 것 같습니다..
FeedVC에서 likeNum이랑 isLiked를 변경해주는데 그게 반영이 안되어서 그러는 것인지도 생각했는데.....😧
또 혹시나 indexPath가 먼가 꼬인 문제일까 해서 indexPath도 FeedCVC의 setLikeLottie를 실행시켜주는 부분에 함께 찍어봤었는데, indexPath는 정상적으로 찍혔습니다..
이상한 것을 정리해보자면..
> 1. 하나의 셀만 보일 때는 좋아요 로티가 작동하지 않던게 조금 스크롤 올려서 두개의 셀이 보이게 되면 잘 작동되는 경우
> 2. 두개의 셀이 보이게 스크롤을 조절해둔 뒤, 좋아요를 아래 셀의 하트를 눌렀을 때 위의 셀에서 하트 로티가 작동되는 경우..
setLikeLottie 함수는 아래처럼, 
함수를 실행했을 때 addSubview 하고, play한 뒤 stop, removeFromSuperview를 하도록 했습니다.
매번 play 안의 print는 정상적으로 실행되는 모습을 보입니다..
```
private func …
```
> [Feat] #210 - 피드 좋아요 로티 문제 해결

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
- Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
🌱 작업한 브랜치
- feature/#231
🌱 작업한 내용
- 스파크 보내기 시에 햅틱을 구현하면서 `SendSparkVC` 와 `SendSparkButton` 커스텀 클래스를 리펙토링.
> 참고: https://zeddios.tistory.com/726
> 현재 selection feedback 인데 강도는 추후에 정해보자. 가장 약한 느낌.
> SendSparkVC
- `empty_enum_arguments` swiftLint 따라 리펙토링
- switch 문으로 같은 코드가 반복되는 것을 forEach 구문에서 조건문을 통해서 구현함.
- 해당 선택된 메시지를 저장하고 넘겨줬던 전역변수 selectedMessage 를 없애고 지역변수로 설정해서 스파크 보내기전에는 불필요한 메모리를 차지하지 않도록 함.
- 코드로 오토레이아웃을 잡아주던 부분을 맨 밑으로 이동시켜 가독성을 올림.
- 접근제어자 추가.
> SendSparkButton
- final 키워드를 통해서 상속시키지 않을 클래스임을 밝힘.
> 이점? 여기참조해주세요! : https://velog.io/@ryan-son/Swift-final-키워드-왜-사용하는걸까
- `public init(type: SendSparkStatus)` 를 통해서 오버로딩 개념으로 UI 를 설정.
> 참고: https://ios-development.tistory.com/44
> 참고: https://ios-development.tistory.com/43
- StatusButton 으로 의미전달이 잘되지 않던 부분을 SendSparkButton 클래스를 만들고, 어떤 …
> [Feat] #231 - 스파크 보내기 시 햅틱 구현

- Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/HabitRoomMemberCVC.xib
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
🌱 작업한 브랜치
- feature/#239
🌱 작업한 내용
- QA 작업
- 습관방 로딩 시 셀을 0개로 하여 깔끔하게 수정
- 구분선 색깔이 제플린에서 스타일이 적용되어 있지 않아서 임의 지정했는데 정해주져서 QA 보드 보고 변경
- QA 의 경우 라벨을 하나 만들테니 적용해주세용~
|기능|스크린샷|
|:--:|:--:|
|습관방|<img src="https://user-images.githubusercontent.com/69136340/153224590-95e97100-295e-4a1f-9413-ed50fc98f0ef.MP4" width ="250">|
- Resolved: #239
> [Fix] #239 - 습관방 로딩 시 셀 초기화 및 구분선 색깔 굵기 및 진하기 수정

- Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
🌱 작업한 브랜치
- feature/#241
🌱 작업한 내용
- 상단의 멘트 중 '습관방' 작은 따옴표 추가
- 텍스트필드 선택시 라인 컬러 변경
- 텍스트필드, count, line 관련 함수 `changeCountLabel` UIViewController+ 에 분리 
- GoalWritingVC, CreateRoomVC, ProfileSettingVC 위의 함수 추가
- 접근제한자 추가
일단 QA 반영했습니다.
그리구 텍스트필드 관련 공통되는 부분을 묶고자 했는데, 엄.... 조금 1이 커질 것 같아서 일단은 
텍스트필드에 따라 countLabel과 lineView가 변경되는 부분만 UIViewController+에 분리했습니다.
그리고 같은 식으로 텍스트필드가 쓰이는 VC에 모두 적용해줬습니다.
건들인 김에 접근제한자도 추가했습니다. 예..
|기능|스크린샷|
|:--:|:--:|
| 나의 목표작성 뷰 | 생략..  |
- Resolved: #241
> [Fix] #241 - 나의 목표 작성 뷰 디테일 수정 및 extension 분리

- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#244
🌱 작업한 내용
새로고침 모션 후 위치가 요상한 문제는 일단 아예 360도를 돌려서 해결했습니다
기존 코드는 에셋 자체를 180도 회전시키고 원래대로 돌려놓는 애니메이션이고, 원래대로 돌려놔야 또 다시 회전이 가능해서 일단은 
아예 360도 냅다 회전시켰슴니다
```
private func refreshButtonAnimtation() {
UIView.animate(withDuration: 0.6,
delay: 0.0,
options: .curveEaseInOut,
animations: {
let rotate = CGAffineTransform(rotationAngle: -3.14)
self.refreshButton.transform = rotate
},
completion: nil)
UIView.animate(withDuration: 0.6,
delay: 0.1,
options: .curveEaseInOut,
animations: {
let rotate = CGAffineTransform(rotationAngle: -(3.14*2.0))
self.refreshButton.transform = rotate
},
completion: { _ in
self.refreshButton.transform = .identity
})
}
```
- 양수를 사용하면 오른쪽으로 반바퀴 회전을 하는데, 저희는 왼쪽으로 회전해야되기 때문에 음수를 붙였습니다.
- 또 애니메이션을 한 번 써서 한번에 `3.14*2.0` 만큼 앵글을 돌릴 수 있을 줄 알았는데, 안되더라구요..
그래서 …
> [Fix] #244 - 대기방 뷰 디테일 수정

- Spark-iOS/Podfile
- Spark-iOS/Podfile.lock
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
🌱 작업한 브랜치
- feature/#252
🌱 작업한 내용
- 수정한 pod을 설치했슴다
- 쉐도우 삭제했슴다
|기능|스크린샷|
|:--:|:--:|
| 홈 플로팅버튼 | <img src="https://user-images.githubusercontent.com/81167570/153707299-13295b1d-3a9d-4c1c-93be-be7073b7d3fa.PNG" width="40%" /> |
- Resolved: #252
> [Add] #252 - 플로팅버튼 라이브러리 재설치

- Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
🌱 작업한 브랜치
- feature/#281
🌱 작업한 내용
- 나의 목표 작성 뷰 두번째 텍스트필드 활성화가 안되는 문제 수정
- 텍스트필드 입력이 끝났을때 하단 버튼과 lineView 색상 변경하는 부분을 분리했습니다.
- 가장 효율적인 코드인지는 모르겠습니다..
|기능|스크린샷|
|:--:|:--:|
| 텍스트필드 |  ![ezgif com-gif-maker (50)](https://user-images.githubusercontent.com/81167570/154705536-d454768b-8266-4d5d-ad52-1c1c138ae72b.gif)  |
- Resolved: #281
> [Fix] #281 - 나의 목표 작성 뷰 두번째 텍스트필드 활성화 안되는 문제 수정

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Source/Classes/BottomButton.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#275
🌱 작업한 내용
**_🚨이 풀리퀘는 일단 제가 좀 더 해보구 마무리 한 뒤, 
한번 더 태그를 해드리든지해서 다시 한번 언급해드리겠슴니다! 그때 확인해주셔두 좋아요!
문제를 만나서 작업 마무리가 조굼 늦어지는데 진행상황정도는 공유하는 것이 좋을것 같아서 일단 냅다 올리고 봅니다.._**
스토리보드에서도 사용하기 위해 타이틀을 설정하는 함수는 `setBottomButtonTitle()` 함수를 따로 분리했습니다.
```
// 버튼 생성
let bottomButton = BottomButton()
// 버튼 타이틀 입력
bottomButton.setBottomButtonTitle(title: "제목입니다")
// 버튼 레이아웃
view.addSubView(bottom)
bottomButton.snp.makConstraints {
// height와 width는 BottomButton에서 적용하기 때문에 상하좌우으로 위치를 잡아주시면 됩니다
}
```
button 객체를 생성해준 뒤, class에 BottomButton을 지정해줍니다
그리구 setUI와 같은 부분에 아래 코드로 타이틀만 넣어주면 되는 것으루 생각했는데 . . .
+) 레이아웃은 하단과 좌우만 잡아주시면 됩니다!
```
.setBottomButtonTitle(titile: "제목임둥")
```
현재 스토리보드 상에서 적용을 해보려구 하니까 일단은 위 코드에서 `Thread 1: EXC_BAD_ACCESS (code=2, address=0x1dadd5de0)` 이 에러가 떠서 지굼 알아보는 중입니다.. …
> [Refactor] #275 - BottomButton 컴포넌트 분리

- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
🌱 작업한 브랜치
- feature/#290
🌱 작업한 내용
- 대기방 토스트메세지 위치 수정
- 대기방 하단 버튼 타이틀 수정
- 사진인증뷰 하단 스택버튼 높이 수정
뷰를 보니까 토스트메세지가 상태바 아래 바로 붙어있더라구여
지금은 대기방에서 코드복사를 하면 시스템 네비바를 사용하고 있기 때문에 네비바의 아래 붙지만
수정될 네비바는 uiview이기 때문에 상관없이 safeArea 기준으로 바로 상단에 붙여두면 되겠다 생각하고 수정했습니다
나중에 네비바가 수정된 후 자연스레 위로 올라가리라 생각합니다..
|기능|스크린샷|
|:--:|:--:|
|GIF|파일첨부바람|
- Resolved: #290 #293
> [Design] #290 - 대기방 토스트메세지 위치 수정, 하단 버튼 타이틀 수정

- Spark-iOS/Spark-iOS/Source/Classes/SparkFlake.swift
🌱 작업한 브랜치
- feature/#296
🌱 작업한 내용
- error 케이스 생성해서 66이상 -1 이하일 경우도 판별하고자 했다.
- Resolved: #296
> [Fix] #296 - SparkFlake 클래스 day66 열거형 분기처리 삭제

- Spark-iOS/Spark-iOS/Resource/Storyboards/Dialogue/Dialogue.storyboard
- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
⛳️ **작업한 브랜치**
- feature/#314
👷 **작업한 내용**
- DialogueVC 에 쉴래요 케이스 추가
- 쉴래요 선택시 다이얼로그 등장
- `setConsiderRestWithAPI` 서버통신에서 dismiss 를 처리중이어서 삭제함
> @yangsubinn @L-j-h-c 
-> 이후, 추가 커밋으로 (33e455d) 서버통신에 있던 dismiss 로직 삭제함. DialogueVC 로 closure 를 넘겼을때 dismiss 가 중복되고 있기때문에 서버코드에서 dismiss 를 분리해냄.
- 다이얼로그 취소 애니메이션은 수빈선배가 전 풀리퀘에서 수정하셨는데 보고싶어서 저도 수정해뒀습니당
|기능|스크린샷|
|:--:|:--:|
|쉴래요 나도..쉴래요|<img src = "https://user-images.githubusercontent.com/69136340/155874692-8c883c09-0936-42ed-a0c7-8763c084ac8c.MP4" width ="250">|
- Resolved: #314
> [Feat] #314 - 쉴래요 다이얼로그 추가

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Resource/Constants/Storyboard.swift
- Spark-iOS/Spark-iOS/Resource/Constants/ViewController.swift
- Spark-iOS/Spark-iOS/Resource/Storyboards/CodeJoin/JoinCheck.storyboard
- Spark-iOS/Spark-iOS/Resource/Storyboards/Create/CreateSuccess.storyboard
- Spark-iOS/Spark-iOS/Source/Classes/BottomButton.swift
- Spark-iOS/Spark-iOS/Source/Extensions/UIViewController+.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
⛳️ **작업한 브랜치**
- feature/#310
👷 **작업한 내용**
-  방 생성 완료 뷰 레이아웃
-  방 생성 플로우 다이얼로그 추가
-  플로우 수정
-  BottomButton 수정
-  대기방 커스텀 액션시트 적용
- 방 생성 완료 뷰에 있는 회색 부분은 일러스트? 로티? 뭐가 들어갈지 모르겠어서 일단은 임의로 imageView 넣어뒀슴니다.
요 친구는 추후에 수정할게여!
- BottomButton setUI 부분을 두가지로 구분했습니다.
하얀색 배경의 버튼인 경우는 `.setUI(.white)` , 핑크색 배경의 버튼은 `.setUI(.pink)`로 사용하시면 됩니다.
- Joincheck 뷰에서 하단의 하얀 버튼 테두리 컬러가 다르다는 디자인의 은밀한 큐에이 전달로 살짝 수정했습니다
- 다이얼로그로 방 생성하고, 방 생성 완료 뷰로 넘어가는 인터렉션은 따로 전달받지 않았고 그냥 맘대로.. 구현했습니다.
원래는 방생성하는 플로우를 dismiss 하고 홈에서 present 시켜서 거기서 대기방가기를 눌렀을 경우 dismiss 후 present 시키는 등등...
present하는 식으로 할까 하다가 그럼 막 띄웠다가 내렸다가 복잡해지는 것 같아서
그냥 push를 해서 화면 전환 코드를 비교적 간단하게 짰습니다..
|기능|스크린샷|
|:--:|:--:|
| 방 생성 완료 후 홈 |<img src = "https://user-images.githubusercontent.com/81167570/155941241-bf5045aa-dad2-4010-bd56-6ab02d7aaea8.gif" width …
> [Feat] #310 - 방 생성 완료 뷰 구현

- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
⛳️ **작업한 브랜치**
- feature/#324
👷 **작업한 내용**
- 로직변경없이 작업하다보니 습관방 리프레시 메서드의 용도가 달라져 네이밍 변경
- `updateMember` -> `updateWithRefreshControl` 변경
- Resolved: #324
> [Refactor] #324 - 습관방 리프레시 메서드 네이밍 변경

- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
- Spark-iOS/Spark-iOS/Source/Classes/SparkActionSheet.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
customActionSheet coverVertical 애니메이션 구현
⛳️ **작업한 브랜치**
- feature/#317
👷 **작업한 내용**
시스템 alert처럼 스르륵 올라가고 내려오는 애니메이션을 구현했습니다..
animate를 써야 했던 이유는 transitionStyle에서 coverVertical로 지정하면 반투명한 배경이 올라가는게 같이 보여버리셔서..
1. 액션시트가 올라온 상태에서 배경을 터치하면 downAnimation이 발동합니다.
2. 현재 액션시트가 사용되고 있는 모든 뷰에서 취소 버튼에 대해서만 animatedDismiss를 적용했습니다.
이유는 다른 버튼을 선택했을 때에는 crossDisolve로 사라지고 특정한 액션이 취해지는 모습이 나름 자연스러워 보였기 떄무네...
(ex : '앨범에서 선택하기'를 터치하면 앨범이 올라오기 때문에 downAnimation이 크게 중요하지 않다...는 개인적인 판단)
3. upAnimation은 항상 발동합니다.
```swift
/// 정의
func animatedDismiss(completion: (() -> Void)? = nil) {
downAnimation()
completion?()
}
/// 사용
alert.addAction(SparkAction("취소", titleType: .blackBoldTitle, handler: {
alert.animatedDismiss(completion: nil)
}))
```
요렇게 생겼습니다. 사용하실 때에 원하시는 컴플리션 넣어주시면 됩니다!
```swift
override func …
```
> [Feat] #317 - customActionSheet coverVertical 애니메이션 구현

- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/DialogueVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
⛳️ **작업한 브랜치**
- feature/#350
👷 **작업한 내용**
- 로그아웃 구현
> 엑세스 토큰을 삭제해주고 로그인 뷰로 이동시켰습니다.
- 로그아웃 다이얼로그는 임의로 만들었고, 문구가 정해지면 수정하겠습니당
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/69136340/157098563-281cd18f-be9b-49ec-9dee-8602efc66ccc.MP4" width ="250">|
- Resolved: #350
> [Feat] #350 - 로그아웃 구현

- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift
⛳️ **작업한 브랜치**
- feature/#368
👷 **작업한 내용**
방생성 완료 뷰 로티 추가
- 로티가 내부 마진 값을 갖고 있어서... 제플린의 티겟 사이즈에 맞추니 넘어온 디자인보다 사이즈가 작았습니다
- 그래서 눈대중으로 비슷하게 맞췄습니다
|기능|스크린샷|
|:--:|:--:|
| 방 생 성 완 료 |<img src = "https://user-images.githubusercontent.com/81167570/157702404-b3cb14cb-9257-4188-9b79-93b2cb712774.jpeg" width ="250">|
- Resolved: #368
> [Design] #368 - 방생성 완료 뷰 로티 추가

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeActiveCVC.swift
- Spark-iOS/Spark-iOS/Source/Cells/Notice/NoticeServiceCVC.swift
- Spark-iOS/Spark-iOS/Source/NetworkModels/Notice/ActiveNotice.swift
- Spark-iOS/Spark-iOS/Source/NetworkModels/Notice/ServiceNotice.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeAPI.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeService.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
⛳️ **작업한 브랜치**
- feature/#364
👷 **작업한 내용**
- 하나의 컬렉션뷰를 사용하면서 전환하다보니 
스크롤한 뒤 전환하고 `scrollToTop`을 하면 `index` 에러가 떴습니당
- 실행 순서 문제일 것 같아서 `DispatchQueue`를 사용했는데, 작업이 끝난 뒤 실행되는 느낌이 아니라
좀 더 확실하다고.. 생각된 `DispatchGroup` 을 사용해서 한 작업을 끝나고 하도록 했습니다.. 맞겠죠?
- 일단 하긴 했는데 완벽하게 해결됐다고는 장담 못하겠습니다.. 나중에 QA 때 개선해야될 것 같습니다..
--
`scrollToTop`을 할 때 `animate`를 `true`로 할지 `false`로 할지 .. 뭐가 더 나을지 모르겠네욤 
아래 스크린샷 보시고 뭐가 더 나을지 의견 남겨주세용
|기능|스크린샷|
|:--:|:--:|
| animate `false` |<img src = "https://user-images.githubusercontent.com/81167570/157830681-9cd026b7-28aa-40c9-be84-e47a83bed5cd.gif" width ="250">|
| animate `true` |<img src = "https://user-images.githubusercontent.com/81167570/157830854-230c8527-da9a-41b7-ade4-b6fa2ac00656.gif" width ="250">|
- Resolved: #364
> [Feat] #364 - 알림뷰 서버 연결

- Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
⛳️ **작업한 브랜치**
- feature/#396
👷 **작업한 내용**
- 스파크 사용 가이드 / 약관 및 정책 선택 시 인앱에서 사파리가 연결되도록 했습니다!
- 노션이 안열린다는 이슈를 염려했는데 그런거 없이 잘 열렸습니다! 아요는 해당하지 않나봐여
- 메일과 동일하게 인앱 느낌을 강하게 내기위해서 `modalPresentaionStyle` 을 `pageSheet` 으로 설정했습니다.
- 기본적으로 사파리가 push 로 화면전환이 진행되요! 그런데 이 부분을 해결하기 위해서 `transitioningDelegate` 를 채택해서 본 뷰컨에서 다루어주는 방법으로 `modalPresentaionStyle` 을 적용했습니다!
|기능|스크린샷|
|:--:|:--:|
|사파리 인앱연결|<img src = "https://user-images.githubusercontent.com/69136340/158583182-b0dfc061-29ad-48c8-b0fd-492c9dbad33b.MP4" width ="250">|
- Resolved: #396
> [Feat] #396 - 스파크사용가이드, 약관 및 정책 노션 인앱 연결

- Spark-iOS/Spark-iOS/Resource/Storyboards/TabBar/Base.lproj/Home.storyboard
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
⛳️ **작업한 브랜치**
- feature/#410
👷 **작업한 내용**
- 커스텀 탭바의 위치는 안전영역위로 54 높이를 가지고있기때문에 홈 컬렉션뷰의 하단을 안전영역으로부터 54 잡아주었습니다.
- 플로팅 버튼이 티켓 생명을 가리기 때문에 하단 인셋이 늘어났고 제플린에서 확인해보니 100이기때문에 적용해주었습니다.
다음을 참고했어요...
|기능|스크린샷|
|:--:|:--:|
|홈|<img src = "https://user-images.githubusercontent.com/69136340/159148900-1f8bc9d6-6126-4a3e-92a3-2d51534f71b0.MP4" width ="250">|
- Resolved: #410
> [Design] #410 - 홈 하단 inset 조절 및 커스텀 탭바에 맞추기

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
⛳️ **작업한 브랜치**
- feature/#412
👷 **작업한 내용**
- collectionView 하단 레이아웃 수정
- isFirstScroll 조건 수정
`self.feedList.count > self.feedCountSize`
이럴 경우, 피드가 많은 경우 첫번쨰 footer에서 isFirstScroll이 true라서 
footer에 그 마지막 멘트가 뜨게 됩니다.
그래서 feedList.count가 feedCountSize와 같을때도 isFirstScroll 을 false로 하도록 했슴니다
... 말이 정리가 안되네여 긁적..
|기능|스크린샷|
|:--:|:--:|
- Resolved: #412 #414
> [Fix] #412 - 피드 레이아웃 및 isFirstScroll 조건 수정

- Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
- Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageDefaultTVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
⛳️ **작업한 브랜치**
- feature/#418
👷 **작업한 내용**
- 스파크 아요 노션과 연결해두었습니다.
- 스파크, 스파크 아요 노션 모두 공개 비활해뒀습니당
🚨 **참고사항**
- 오픈소스 라이브러리 중  카카오, 파이어베이스, 로티 는 아파치 / 나머지는 MIT 였습니다. 내용이 궁금하면 아래를 참고해주세용
> https://selfish-developer.com/entry/오픈소스-라이센스-정리
|기능|스크린샷|
|:--:|:--:|
|마이페이지|<img src = "https://user-images.githubusercontent.com/69136340/159233222-c3d807bd-c847-45cd-b091-07192076cc78.mov" width ="250">|
- Resolved: #418
> [Feat] #418 - 마이페이지 오픈소스 라이브러리 노션 인앱 연결

- Spark-iOS/Spark-iOS/Source/Cells/Home/HomeHabitCVC.swift
⛳️ **작업한 브랜치**
- feature/#420
👷 **작업한 내용**
- se2 / 13 / 13 Pro / 13 Pro Max
- 위의 기기에서 모두 확인했고, 문제 없음을 확인했습니당.
- 왼쪽 flake image 는 스보에서 비율로 잡혀있고, 우측의 ticket image 는 나머지를 채우고있는데요.
- 셀의 크기도 비율로 잡고있어서 fill 로 해도 결국 ticket image 도 비율로 잡힌다고 판단하고 수정했습니다.
- 프로필 크기가 28*28 이었어서 14로 corner radius 로 변경했습니다.
- Resolved: #420
> [Fix] #420 - 홈 티켓 흰줄 제거 및 프로필 모서리 수정

- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthAPI.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
⛳️ **작업한 브랜치**
- feature/#430
👷 **작업한 내용**
- 로그아웃 서버통신 성공
- 카카오 회원탈퇴 api 연결
- 애플의 경우 별도의 회원탈퇴 기능을 제공하지 않고, 기기의 설정에서 연결된 앱을 해제할 수 있도록 하고 있어요! 
|기능|스크린샷|
|:--:|:--:|
|카카오회원탈퇴|<img src = "https://user-images.githubusercontent.com/69136340/160528842-ba476ac5-4b73-4751-8811-f8efa15fd1b0.mp4" width ="250">|
- Resolved: #430
> [Feat] #430 - 마이페이지 로그아웃, 애플/카카오 회원탈퇴 및 서버연결

- Spark-iOS/Spark-iOS/Resource/Constants/Const.swift
- Spark-iOS/Spark-iOS/Resource/Constants/Header.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Feed/FeedService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Home/HomeService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/MyRoom/MyRoomService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Notice/NoticeService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/User/UserService.swift
⛳️ **작업한 브랜치**
- feature/#444
👷 **작업한 내용**
- 재로그인시 이전 계정으로 로그인되는 버그를 해결했습니다!
- Moya Service 헤더가 갱신되지 않았던 문제였습니다.
현재 상태에서 구성하면 Const header 에서 선언한 헤더들이 바뀌지 않음을 확인했고,
다음과 같이 변경하니까 됐습니다.
그런데 이렇게 하면 안됐습니다.
이게 매번 선언해주는게 아닌 변수를 사용하다보니까 그런거 같아요
Const.accessToken 은 유저디폴트를 호출하는 함수가 아니라 그냥 유저디폴트가 가져온 변수를 저장하는 거니까 재호출이 아니라서 갱신이 안되는듯 합니다!
애초에 변하는 값인 UserDefaults 를 Const 에 `타입프로퍼티` 로 둔게 잘못이었던것 같아요
그래서 `타입메서드` 로 구성해서 다시금 UserDefaults 가 재호출되어 갱신된 값을 사용할 수 있도록 했습니다.
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/69136340/160757209-b6542cd8-74f9-4dfa-9834-26b511ff44e8.MP4" width ="250">|
- Resolved: #444
> [Fix] #444 - 재로그인시 이전 계정으로 로그인되는 버그

- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/GoalWriting/GoalWritingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
⛳️ **작업한 브랜치**
- feature/#429
👷 **작업한 내용**
- 나의 목표 작성
- 프로필 설정
- 방 생성 
화면 전환 시 `UITextField.textDidChangeNotification` 노티 삭제
삭제를 안해줄 경우 다른 뷰에 영향을 주는 문제가 호오옥시나 생길까봐 삭제해줫습니다.
|기능|스크린샷|
|:--:|:--:|
- Resolved: #429
> [Chore] #429 - 나의 목표 작성, 프로필 설정, 방 생성 뷰에서 화면전환 시 노티 삭제

- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
⛳️ **작업한 브랜치**
- feature/#452
👷 **작업한 내용**
- 코드로 참여시 대기방에서 홈으로 갈 때 홈 리스트가 조회되지 않았어요
- 코드로 참여하는 뷰가 overfullscreen 으로 보여지기 때문에 홈의 viewWillAppear 가 다시금 호출되지 않았어요 그래서 노티를 사용했습니다.
- 예전에 네비바를 히든하고 팝 스와이프 제스처를 하게되면 루트뷰컨트롤러에서 에러가 발생한다 그래서 확인해줘야한다는
```swift
// MARK: - UIGestureRecognizerDelegate
// FIXME: - 네비게이션 extension 정리후 공통으로 빼서 사용하기
extension HomeVC: UIGestureRecognizerDelegate {
func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
return navigationController?.viewControllers.count ?? 0 > 1
}
}
```
이부분 기억나시나용 지금 홈에서 그렇더라구여 그래서 홈도 이 풀리퀘에서 적용해주었고, 피드와 내 보관함은 문제없더라구요 루트뷰컨이 아니라서 그런가봐요 그래서 탭바를 히든해도 별 상관이 없는거죠 그래서 이 부분을 extension으로 정리하고 싶네여
좀 더 고민해보고 이슈를 파서 진행할게여!
- Resolved: #452
> [Feat] #452 - 대기방에서 홈으로 갈 때 습관방 리스트 조회하기

- Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
⛳️ **작업한 브랜치**
- feature/#400
👷 **작업한 내용**
- 액세스토큰의 갱신을 위해서 doorBell API 를 스플래쉬 뷰컨트롤러에서 호출합니다. 이를 통해 매 접속시마다 액세스 토큰을 갱신합니다.
> 추후 업데이트를 통해서 토큰 만료의 경우를 대비하는 API 를 붙일 예정입니다.
- 성공적으로 doorBell API 를 통해서 스플래쉬 뷰컨트롤러에서 액세스 토큰을 받고, 갱신해서 홈에서 호출해주는 것을 볼 수 있습니다!
- Resolved: #400
> [Feat] #400 - SplashVC 에서 doorbell API 로 엑세스 토큰 갱신하기

- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthAPI.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
⛳️ **작업한 브랜치**
- feature/#468
👷 **작업한 내용**
- 회원 탈퇴 서버통신 연결
|기능|스크린샷|
|:--:|:--:|
|회원탈퇴|<img src = "https://user-images.githubusercontent.com/69136340/161241569-31feff2f-5c4a-49a6-ab63-7f44280a4b54.MP4" width ="250">|
- Resolved: #468
> [Feat] #468 - 회원 탈퇴 서버통신 연결

- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
⛳️ **작업한 브랜치**
- feature/#471
👷 **작업한 내용**
- 팝업창 subtitle 가운데 정렬하기
|기능|스크린샷|
|:--:|:--:|
|팝업|<img src = "https://user-images.githubusercontent.com/69136340/161372493-49274d6d-7034-4dec-aed6-16da062a3bf3.PNG" width ="250">|
- Resolved: #471
> [Fix] #471 - 팝업창 subtitle 가운데 정렬하기

- Spark-iOS/Spark-iOS/Resource/Constants/UserDefaultsKey.swift
- Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
⛳️ **작업한 브랜치**
- feature/#476
👷 **작업한 내용**
- 습관 인증 스톱워치 백그라운드에서 멈추는 문제 해결
- 자그마한 함수 순서 변경 및 이름 변경
일단은 백그라운드에 있는 경우에도 스톱워치가 작동하도록 하기 위해
background로 들어갈 때, foreground로 들어올때의 시간차를 초 단위로 구해
기존의 currentCountTime이라는 초 단위의 친구에게 더해주도록 했습니다.
+ 일단은 백그라운드에 두더라도 앱이 갱신되지 않는 시간 내에는 문제 없이 작동하도록 했습니다.
백그라운드에 뒀다가 앱 자체가 갱신돼서 스플래시부터 시작하는 경우는 따로 이슈를 만들어서 고민해봐야 할 것 같습니다.
|기능|스크린샷|
|:--:|:--:|
|-|<img src = "https://user-images.githubusercontent.com/81167570/161437167-a0735ae1-0e4e-4013-accc-0d90d9b92e2a.gif" width ="250">|
- Resolved: #476
> [Fix] #476 - 습관 인증 스톱워치 백그라운드에서 멈추는 문제 해결

- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
⛳️ **작업한 브랜치**
- feature/#462
👷 **작업한 내용**
- 이모지 키보드로 전환 시 원래의 간격만큼 프로필 이미지 뷰와 닉네임 라벨이 움직이도록 수정
- 프로필 이미지가 위로 올라간 상태에서 키보드를 내리면 다시 돌아오도록 애니메이션
1. Layout 설정 위치 변경 & originY를 바꿔주는 방식으로 변경 :  기존에 키보드 등장 시 Snapkit으로 Layout을 잡아주는 방법은 View Layout Cycle에 의해 y좌표가 여러번 바뀌어야 하는 상황에서 유효하지 않았음.
2. @objc `keyBoardDidHide` : 유저네임 라벨과 프로필 이미지뷰의 위치가 변한 경우 원래 좌표를 기억해주기 위해 `originalY` 변수 초기화, 키보드가 완전히 올라온 다음에 `keyBoardFrameDidChange` 메서드를 사용하기 위해 `canChangeKeyBoardFrame` 변수 초기화 
3. @objc `keyBoardFrameDidChange` : 키보드가 등장하고, 이모지 키보드로 전환된 경우에만 y좌표의 차이를 `originYDif` 변수에 저장. `originYDif` 변수에 올바른 값이 저장되면 `purposedY`에 이를 다시 할당. 이모지 키보드로 전환될 때마다 `purposedY`의 값을 반전시켜서 `userNameLabel`과 `profileImageView`가 위아래로 움직이도록 함
4. @objc `keyBoardWillHide` : 프로필이미지뷰가 위로 올라간 경우 원래 위치로 돌아가도록 하는 애니메이션 설정
|기능|스크린샷|
|:--:|:--:| …
> [Feat] #462 - 스파크 보내기 뷰 이모지 키보드 관련 레이아웃 대응

- Spark-iOS/Spark-iOS/Source/ViewControllers/StorageMore/StorageMoreVC.swift
⛳️ **작업한 브랜치**
- feature/#470
👷 **작업한 내용**
- 대표이미지 변경 뷰에서 Rest, None 상태의 티켓이 보이지 않도록 필터링
- 변경되는 이미지가 선택되지 않았더라도 완료버튼이 눌리도록 하기
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/77208067/162698694-2b2b2fec-e87e-426a-a89f-022cd698ef3d.mp4" width ="250">|
|GIF|<img src = "https://user-images.githubusercontent.com/77208067/162698714-3348d5ce-9bb1-4dff-b5a3-4ee1625a2ac4.mp4" width ="250">|
- Resolved: #470
> [Feat] #470 - 대표이미지 변경 뷰 셀 필터링 및 완료버튼 동작 수정

- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/WithdrawalVC.swift
⛳️ **작업한 브랜치**
- feature/#523
👷 **작업한 내용**
- 회원 탈퇴 체크 박스 선택시 텍스트 컬러 변경했습니다.
- spark dark gray -> spark deep gray(활성화)
|기능|스크린샷|
|:--:|:--:|
|회원탈퇴|<img src = "https://user-images.githubusercontent.com/69136340/163105668-df552f84-dd82-4d28-b925-ebec6ab66062.MP4" width ="250">|
- Resolved: #523
> [Fix] #523 - 회원 탈퇴 체크 박스 선택시 텍스트 컬러 변경

- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
⛳️ **작업한 브랜치**
- feature/#528
👷 **작업한 내용**
프로필 수정 뷰의 willDisappear에서 observer을 지워줬습니다.
이제 제가 알고 있는 텍스트 필드가 있는 뷰에는 전부 노티를 삭제해준 것 같습니다..
이젠 진짜 텍필 노티 관련 문제가 없을 것이라 믿습니다..
|기능|스크린샷|
|:--:|:--:|
- Resolved: #528
> [Fix] #528 - 프로필 수정 뷰 노티 삭제

- Spark-iOS/Spark-iOS/Resource/Constants/URL.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Splash/SplashVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
⛳️ **작업한 브랜치**
- feature/#511
👷 **작업한 내용**
- 현재 앱 버전과 https://itunes.apple.com/lookup?bundleId=(번들아이디) 의 JSON 중 results 의 version 을 비교해서 업데이트 alert 창을 띄우도록 했습니다.
- 현재 a.b.c 버전에 대해서 a 와 b 버전만 비교해서 낮을 경우 업데이트 했습니다.
> 이는 추후에 업데이트 규칙이 정해지면 수정하겠습니다.
- itms-apps://itunes.apple.com/app/(app store connect 앱정보의 apple id) 을 통해서 URL Scheme 방법으로 앱스토어를 열도록 했습니다.
- 이슈에 관련 참고 자료 출처를 달아두었습니당
|기능|스크린샷|
|:--:|:--:|
|업데이트|<img src = "https://user-images.githubusercontent.com/69136340/163604401-c7c9c0c3-ee19-4f44-ad11-de5f81d6d501.mp4" width ="250">|
- Resolved: #511
> [Feat] #511 - 현재 앱 버전 확인 후 최신 업데이트 안내

- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
⛳️ **작업한 브랜치**
- feature/#534
👷 **작업한 내용**
방 생성 뷰 노티 추가, 삭제하는 시점 수정
willAppear과 didDisappear 에 각각 추가하고 삭제하도록 했습니당
|기능|스크린샷|
|:--:|:--:|
- Resolved: #534
> [Fix] #534 - 방 생성 뷰 노티 추가, 삭제하는 시점 수정

- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
⛳️ **작업한 브랜치**
- feature/#480
👷 **작업한 내용**
- `keyboardWillChangeFrameNotification` 을 통해서 키보드 프레임이 변경될 때 키보드가 가리는지 가리지 않는지 여부를 판단해서 `profileImageView` 의 top constraint 를 업데이트 하는 로직으로 구성했습니다.
``` swift
// keyboardWillChangeFrameNotification - Posted immediately prior to a change in the keyboard’s frame.
NotificationCenter.default.addObserver(self, selector: #selector(updateKeyboardFrame(_:)), name: UIResponder.keyboardWillChangeFrameNotification, object: nil)
```
- 프로필 설정 뷰에서는 titleLabel 까지 침범하는 경우가 있어 이부분은 프로필 설정뷰에서만 대응해주었습니다.
- 시뮬에서는 입력하기만 해도 `keyboardWillChangeFrameNotification` 가 post 되서 이상한대 실기기에서는 안그러더라구요. 참고해주세용.
- 키보드가 올라와도 line view 를 가리지 않아서 line view 가 키보드에 붙는 상황도 있었는데 대응해줌.
- 프로필 설정 시 이모지 키보드에서 프로필 사진이 넘어가는 것도 대응해줌.
> 커밋하고 몇번이나 고쳐서 최종 코드를 보시는게.. 좀 더 눈에 편하실겁니당.
|기능|스크린샷| …
> [Feat] #480 - 프로필 설정 및 생성뷰 이모지 키보드 레이아웃 대응

- Spark-iOS/Podfile
- Spark-iOS/Podfile.lock
- Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
⛳️ **작업한 브랜치**
- feature/#525
👷 **작업한 내용**
- RxSwift, RxCocoa pod install
- throttle로 알림뷰 버튼 중복 탭 막음
**두 개의 버튼 각각 처음 버튼을 누른 3초 동안의 탭이 막았습니다.**
- 와다다 연속적인 탭이 안되기 때문에 전에 비해 터지지는 않지만, 버튼이 안먹는다는 느낌이 들기도 해서 시간을 줄이거나 해야되나 싶습니다..
- 시간을 줄일 수록 더 연속적으로 탭이 가능해지기 때문에 터질 가능은 증가합니다..
**debounce가 아닌 throttle을 쓴 이유**
- debounce는 시간을 2초로 설정하면 2초 동안 여러번의 이벤트를 받더라도 딱 한 번의 이벤트를 방출하는 친구입니다.
- 마지막에 한 번의 이벤트를 방출하기 때문에 최초 탭을 하더라고 2초 후 이벤트가 발생합니다
- 그래서 안썼습니다 예..
**하고 시픈 말이 있어**
- 확인해주시면 setAddTarget 등의 주석 삭제하고 머지하겠습니다
- 추가적으로 좀만 더 좋은 중복 방지 방법이 있는지 공부하고 몇 개 더 시도해보고 천천히 머지하겠습니다..
|기능|스크린샷|
|:--:|:--:|
- Resolved: #525
> [Feat] #525 - RxSwift, Rxocoa pod install 및 throttle로 알림뷰 버튼 중복 탭 막음

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
⛳️ **작업한 브랜치**
- feature/#544
👷 **작업한 내용**
- 아래로 당겨서 리프레쉬할때 스크롤해서 방을 fetch 하는 것과 방을 fetch 하는 중복되는 현상 발생했어요.
- 그래서 스크롤할때 방을 fetch 하던 로직을 아래로 스크롤로 로직을 변경했습니다.
```swift
// 문제의 코드
// 이럴때 대기방이 1개이고, 아래로 당겨서 리프레쉬 할때 contentOffset 은 음수가 되서 해당 블록이 실행되지 않는다고 생각했지만,
// 대기방이 적어서 contentSize.height 가 작고, 스크롤뷰의 높이까지 빼주면 음수보다 더 작아질 수 있는 경우가 있었습니다.
if scrollView.contentOffset.y > scrollView.contentSize.height - scrollView.bounds.height {
```
- 피드에서는... 저번에 고쳤더라구용 그래서 같은 로직을 사용했던 홈에서만 적용해주었습니당.
|기능|스크린샷|
|:--:|:--:|
|해결 전|<img src = "https://user-images.githubusercontent.com/69136340/164167449-5d5b7ca4-b535-488e-b610-f65aab3704cc.mp4" width ="250">|
|해결 후|<img src = "https://user-images.githubusercontent.com/69136340/164167508-f5eb0ba0-2b5c-4176-9c8c-9016374221b4.mp4" width ="250">|
- Resolved: #544
> [Fix] #544 - 홈에서 리프레쉬할 때 엠티뷰가 등장하는 버그

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
⛳️ **작업한 브랜치**
- feature/#549
👷 **작업한 내용**
방 삭제 시 보내는 노티에 isHost 라는 키값을 추가했고 삼항연산자로 homeVC에서 분기처리해줬습니다.
나중에 문구 확정되면 문구만 쇽샥 바꾸겠습니다.
https://user-images.githubusercontent.com/81167570/164610392-ac806308-8aef-4781-805d-056825902dda.mov
- Resolved: #549
> [Fix] #549 - 대기방 개설자 방 삭제 시 토스트메세지 분기처리

- Spark-iOS/Spark-iOS.xcworkspace/contents.xcworkspacedata
- Spark-iOS/Spark-iOS/Source/Cells/Mypage/MypageProfileTVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/MypageVC.swift
⛳️ **작업한 브랜치**
- feature/#539
👷 **작업한 내용**
- 홈 에서 마이페이지로 갈때는 `profileImage` 가 nil 이기 때문에 서버통신을 통한 URL 을 통해서 프로필 셀과 프로필 수정 뷰로 변수를 전달해준다.
- 프로필 수정에서 마이페이지로 갈때는 `profileImage` 를 델리게이트로 넘겨줘서 로컬에서 변경하도록 했다.
- 서버통신은 마이페이지로 갈때 최초 한번. 프로필 수정에서 완료 버튼을 눌렀을때 작동한다.
- 마이페이지 프로필 셀은 초기화 메서드가 두개이다.
- 서버통신을 통해 얻은 URL 로 초기화
- 프로필 수정을 통해서 로컬로 이미지를 변경해서 초기화
- profileImage 가 nil 이 아닌 경우는 프로필 변경 후 마이페이지로 돌아올 때이다. 왜냐면 프로토콜로 UIimage 가 전달되어 profileImage 가 nil 이 아닌 것이다. 이때만 로컬로 이미지를 변경해주었다.(프로필을 변경하고 바로 프로필 URL 을 다운로드하면 404 에러가 등장했기 때문)
|기능|스크린샷|
|:--:|:--:|
|프로필 변경|<img src = "https://user-images.githubusercontent.com/69136340/164991985-92165cea-b170-4125-be10-072897a88090.mov" width ="250">|
- Resolved: #539
> [Fix] #539 - 마이페이지에서 기본프로필의 경우 가끔 보이지 않는 버그

- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/CompleteFailDialogueVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Dialogue/LifeDiminishDialogueVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
⛳️ **작업한 브랜치**
- feature/#567
👷 **작업한 내용**
- 홈 미완료 / 완료 방 팝업 `확인했어요` 버튼에 햅틱 추가
- 습관방 생명 감소 팝업 `확인했어요` 버튼에 햅틱추가
- 습관방 `오늘의 인증` 버튼에 햅틱 추가
- 스파크 보내기 햅틱 효과 강화
- 스파크 보내기 햅틱은 selection 에서 impact 피드백 으로 변경하였습니다.
Impact haptics 는 시각적 경험을 보완하는데 사용할 수 있는 물리적 메타포를 제공한다. 예를 들어 사람들은 view 가 제자리에 고정될 때 탭을 느끼거나 두 개의 무거운 물체가 충돌할 때 쿵 소리를 느낄 수 있습니다.
Selection haptics 는 UI 요소의 값이 변경되는 동안 피드백을 제공한다.
> 그래서 selection 을 사용했는데 너무 약했네용 그래서 impact 에서 제일 약한 light 를 사용했습니다.
- HIG 문서에서 햅틱을 경험할 수 있습니당~ 
> [HIG - haptic](https://developer.apple.com/design/human-interface-guidelines/ios/user-interaction/haptics/)
- Resolved: #567
> [Feat] #567 - 홈, 습관방에 haptic 추가

- Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/CompleteAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/StorageVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
⛳️ **작업한 브랜치**
- feature/#577
👷 **작업한 내용**
- 트래킹 이벤트의 이름을 select_item 에서 각 이벤트의 고유한 이름으로 변경해주었습니다.
|기능|스크린샷|
|:--:|:--:|
|수종사항|<img src = "https://user-images.githubusercontent.com/69136340/165753828-6bc7214d-371f-4c66-ac50-714857dec3f4.png" width ="250">|
- Resolved: #577
> [Fix] #577 - 트래킹 이벤트 item name 변경

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
⛳️ **작업한 브랜치**
- feature/#579
👷 **작업한 내용**
- 앱에서 카메라를 열거나, 오려두기 복사하기 등 영어로 언어가 설정되어서 앱의 언어를 바꿔주었습니다.
- 앱이 출시되면 다음과 같이 EN 표시가되기 때문에 한글로 바꿔주기 위해서 세팅했습니다.
- 다음과 같이 `Localization native development region` 를 Korea 로 설정해주면 됐었는데..! 안되더라구요?
- 그래서 위를 보시면 `$(DEVELOPMENT_LANGUAGE)` 를 언어로 받기 때문에 `Spark-iOS.xcodeproj` 를 비주얼 스튜디오 코드(다른 에디터 프로그램이면 다 가능)로 열어서 `developmentRegion` 를 kr 로 변경했습니다!
출처:
> https://yannichoongs.tistory.com/231(원래 이 방법을 사용했었음... 근데 적용이 안되네여 ㅜ)
> https://jinsangjin.tistory.com/157
> https://lxxyeon.tistory.com/133
- Resolved: #579
> [Chore] #579 - 앱 언어 Korea 변경

- Spark-iOS/Spark-iOS/Source/ViewControllers/Mypage/EditProfileVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Profile/ProfileSettingVC.swift
⛳️ **작업한 브랜치**
- feature/#559
👷 **작업한 내용**
- 프로필 변경
- 프로필 설정(회원가입)
- 두군데에 사진을 업로드하는 시간이 길어져서 사용자에게 사용성을 해치므로 로딩창을 추가했습니다.
- 어차피 화면전환되서 뷰에서 remove 안해주려했는데 앗! 메모리문제가 있으려나~ 했는데 프로필 변경은 dismiss 로 메모리에서 해제되고, 프로필 설정또한 `fullScreen` 으로 화면전환을 해서 `viewDidDisAppear` 되기 때문에 remove 코드는 작성하지 않았습니당!
|기능|스크린샷|
|:--:|:--:|
|프로필 수정 로딩|<img src = "https://user-images.githubusercontent.com/69136340/165977262-c39de0ce-c6fd-4988-8cd5-54cb2fb7e2cc.mov" width ="250">|
- Resolved: #559
> [Feat] #559 - 프로필 수정 완료 후 로딩뷰 추가

- Spark-iOS/Spark-iOS/Resource/Constants/Tracking.swift
- Spark-iOS/Spark-iOS/Source/AppDelegate.swift
⛳️ **작업한 브랜치**
- feature/#582
👷 **작업한 내용**
- 푸시알림으로 앱을 열 경우 추적
```swift
스파크알림 - spark
인증알림 - certification
리마인드 알림 - remind
습관방 시작 알림 - roomStart
고민중 - consider
```
에 대해서 notification_open_... 로 이벤트 이름 지정했습니다.
- 실시간에서는 확인되는데 대시보드에서는 확인이 안되긴하네용... 좀 뒤에 적용되려나 싶네요!
|기능|스크린샷|
|:--:|:--:|
|트래킹|<img src = "https://user-images.githubusercontent.com/69136340/166100479-9dc5c984-fc68-477d-9b90-9a997b5f61a0.png" width ="250">|
- Resolved: #582
> [Feat] #582 - 푸시알림으로 앱을 열 경우 트래킹

- Spark-iOS/Spark-iOS/Source/AppDelegate.swift
- Spark-iOS/Spark-iOS/Source/Cells/HabitRoom/SendSparkCVC.swift
- Spark-iOS/Spark-iOS/Source/Protocols/SendSparkCellDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/SendSparkVC.swift
⛳️ **작업한 브랜치**
- feature/#587
👷 **작업한 내용**
- 메시지를 입력해서 보내는 `스파크보내기` 의 경우는 완전히 보내졌을 때 트래킹이 되야한다. 지금 현재는 각 스파크 보내기 버튼들을 선택하면 트래킹되고 있다.
- 이 부분을 메시지 입력 후 `보내기`, 키보드 `전송` 을 눌렀을 때 트래킹 하도록 변경했습니당
- SwiftLint 워닝도 트래킹 관련 풀리퀘이기 때문에 추가로 해결해두었습니다.\
> 문자열 열거형은 enum case 이름과 동일할 때 생략 가능하다.
- 해당 SwiftLint 워닝 참고 페이지
> [Redundant String Enum Value](https://realm.github.io/SwiftLint/redundant_string_enum_value.html)
- Resolved: #587
> [Fix] #587 - 스파크 보내기 트래킹 수정

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/FeedVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
⛳️ **작업한 브랜치**
- feature/#547 
👷 **작업한 내용**
- list 라는 네이밍보다 복수를 사용하도록 권유되어서 habitRooms 로 네이밍 변경
- list 라는 네이밍보다 복수를 사용하도록 권유되어서 feeds 로 네이밍 변경
> 예를들어 nameTextString 이 아닌 nameText 로 변수명에서 직접적으로 해당 타입을 의미하는 네이밍 컨밴션은 권유되지 않는다고 해요!
> 그래서 배열에 list 를 붙이는것이 아닌 복수로써 사용하더라구요.
- 탭바를 빠르게 전환시 이전 서버통신이 종료되고 append 를 통해서 새로운 서버통신의 결과와 중복으로 추가되기때문에 UI 와 출동해서 비정상종료가 발생했는데 viewWillAppear 에서 append 가 아닌 대체해서 해결
- 서버 통신을 취소해주는 작업도 생각을 해봤는데 moya 에서 아예 지원을 하지 않는 것은 아니고 아래 이슈를 보면 `.cancel()` 메서드를 통해서 가능은 한데(moya 에서 서버통신을 요청하는 request 를 취소하는 방법) 저희는 Service 라는 파일에서 provider 를 통해서 request 를 만들다보니까 이걸 호출하는 뷰컨에서 저장하거나 또 탭바가 전환됨을 추적하기에 쉽지 않다고 판단했어요!
> https://github.com/Moya/Moya/issues/1023
- 그래서 애초에 문제였던 append 하는 방법에 대해서 의문을 가졌고, 초기에는 last id 도, 저장했던 배열들도 다 덮어씌어줘도 된다고 생각했어요! 그래서 서버통신이 끝난 후 newFeeds, …
> [Bug] #547 - 탭바 이동 후에 습관방 복제 및 강제종료 해결

- Spark-iOS/Spark-iOS/Source/ViewControllers/Notice/NoticeVC.swift
⛳️ **작업한 브랜치**
- feature/#593
👷 **작업한 내용**
알림 뷰 스크롤할 때 버튼 전환시 터지는 문제 해결
`isActivity`에 따라 `numberOfItemsInSection` , `cellForItemAt` 등 `reloadData`할때 필요한 부분들을 분기처리했는데, 
`isActivity` 시점이 서버 통신 전에 있었어서 서버 통신 이후 `reloadData` 전으로 옮겨줬습니다
|기능|스크린샷|
|:--:|:--:|
- Resolved: #593
> [Fix] #593 - 알림 뷰 스크롤할 때 버튼 전환시 터지는 문제 해결

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
⛳️ **작업한 브랜치**
- feature/#601
👷 **작업한 내용**
- 앱 언어 카누리어(kr) 에서 한국어(ko)로 변경
여러 글들에서 http~ 주소를 사용하게 되면 어떨때는 뜨고 어떨때는 안된다는 내용이 있었고, 최신화가 되지 않는 이유로 https~ 로 변경해주면 반영이 된다고 했어요!(앱스토어에 완전히 반영이 되려면 24시간정도 걸린다고 하고.. http~ 의 경우는 https~ 보다 늦다고 한다.)
그런데..! https 로 설정해두니 웹 페이지에서 파일은 다운로드 되는데 해당 코드에서 프린트 해보니 다른 파일(출시 이전처럼 내용들이 비어있는 파일)을 다운로드하고 있었어요..(이건 참 이상하다..)
그래서 http 로 변경했더니 잘됐습니당!(...어째서...?) 그래서 이것도 참고해두면 좋을 것 같아요.
---- 24시간 후
24시간이 지난 후에 https~ 확인해보니까! 정상적으로 동작하였어요!...! 참고해두면 좋을 것 같아요.🙂
|기능|스크린샷|
|:--:|:--:|
|버전 확인|<img src = "https://user-images.githubusercontent.com/69136340/167259759-53083456-0523-4b3b-aaaf-cfab202df6f7.png" width ="400">|
- Resolved: #601
> [Chore] #601 - 앱 언어 변경

- Spark-iOS/Spark-iOS/Source/Classes/SendSparkButton.swift
⛳️ **작업한 브랜치**
- feature/#571
👷 **작업한 내용**
- 불필요한 오버라이드하던 생성자 삭제.
- UI 가 변경되면서 사용하지 않던 `isSelected` 삭제.
- `didset` property observer 를 통해서 content 설정
- 자식클래스에서 초기화를 하는 과정은 다음과 같이 진행해야해요!
1.자식 클래스의 프로퍼티 초기화
2.부모 클래스의 초기화 메서드 호출
3.자식 클래스의 나머지 초기화 동작 (메서드 등)
덮어씌워지지 않기 위해서입니당.
그래서 위와 같이 이니셜라이저를 수정했습니당.(2단계 초기화로 검색하면 좀 더 자세하게 얻을 수 있을거에용)
편의 이니셜라이저가 지정이니셜라이저를 호출하고 지정이니셜라이저는 부모의 지정이니셜라이저를 호출하게되요! 그리고  subclass 아래로 내려오면서 프로퍼티에 접근할 수 있게되요! 그렇다면 코드에서처럼 `super.init()` 이전의 값 설정은요? -> 저장프로퍼티에 대해서 초기화를 하지 않은채로 지정이니셜라이저를 호출할 수 없기때문에! 순서가 지켜져야해요! 그후에 self 에 접근이 가능하다고 하네요!
> 초기화 (Initialization) 참고로 공부하면서 했어요! 
> https://jusung.gitbook.io/the-swift-language-guide/language-guide/14-initialization
- Resolved: #571
> [Refactor] #571 - SendSparkButton 이니셜라이저를 활용한 초기화로 리펙토링

- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
⛳️ **작업한 브랜치**
- feature/#618
👷 **작업한 내용**
- 기존에 habitRooms 의 count 가 1이 아닐경우만 대응해주고 0일 경우를 대응하지 않았다. 왜냐면, 서버통신 코드에서 현재 현재 습관방 목록과 새로 가져온 습관방의 목록이 비었을때만 엠티뷰를 세팅해줬다. 그런데  ***습관방 목록이 한 개일 때 삭제(실패 확인, 방 삭제, 나가기) 하고 홈으로 와서 새로고침을 하게 되면 현재 습관방 목록은 한 개고(로컬데이터) 새로 가져온 습관방 목록은 비어있기 때문에 엠티뷰가 아닌 한개의 목록이 등장했다.***
- 위의 점으로 버그를 파악했고, 서버통신에서 UI 를 통제하던 메서드를 분리해서 순전히 `habitRooms` 만 갱신하는 역할인 `newHabitRooms` 에 저장해주었습니다.
- 습관방 목록을 가져오는 서버통신이 사용되는 모든 곳의 completion 에 분기처리를 다시금 해주었습니당
|기능|스크린샷|
|:--:|:--:|
|실패 후 새로고침|<img src = "https://user-images.githubusercontent.com/69136340/168652137-92095386-adea-4783-9710-de5cfeb8b646.mp4" width ="250">|
~**대기방 나가기, 방 나가기 모두 확인했고, 내일 밤...12시... 실패방 확인하기 후 스크린샷 올리고 태그할게용**~
- Resolved: #618
> [Bug] #618 - 습관방 한 개일 때 삭제(실패, 방 삭제, 나가기) 후, 새로고침 후 사라지지 않는 버그

- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
⛳️ **작업한 브랜치**
- feature/#608
👷 **작업한 내용**
- doorbellAPI 에서 os 키값을 가지고 `ios` 넘겨주었습니다.
- 서버에서 해당 사용자의 OS 정보를 가지고 있으면 앞으로 다양한 활동에 유리하다고 판단하고 api 를 변경하셨다고 합니당.
> 시스템적인 공지 및 홍보 등 OS 구별되게 푸시알림으로써 보낼 수 있다는 점이 장점이라고 하셨습니당
|기능|스크린샷|
|:--:|:--:|
|postman - doorbell API|<img width="1000" alt="스크린샷 2022-05-16 오후 5 16 16" src="https://user-images.githubusercontent.com/69136340/168549196-698d66ec-6e67-4af6-9d62-b98309e954a6.png">|
- Resolved: #608
> [Feat] #608 - 스플래시 뷰에서 OS 정보 서버로 보내기

- Spark-iOS/Spark-iOS/Source/NetworkServices/Auth/AuthService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/User/UserService.swift
⛳️ **작업한 브랜치**
- feature/#631
👷 **작업한 내용**
CompressionQuality 수정
각각 CompressionQuality를 1.0, 0.7, 0.5, 0.3으로 둔 이미지 사이즈입니다.
- 1.0에서 11초, 0.7에서 2.5초, 0.5에서 1.5초 정도 업로드 시간이 소요되었습니다.
- 육안으로 이미지 품질의 차이가 거의 구분되지 않았습니다.
|비율|1.0|0.7|0.5|
|:--:|:--:|:--:|:--:|
|스크린샷|<img src = "https://user-images.githubusercontent.com/77208067/183234116-d86e7726-6e18-48a1-a274-4a84e4a26e26.jpeg" width ="400">|<img src = "https://user-images.githubusercontent.com/77208067/183234115-f621495f-354a-4d09-a258-585384939707.jpeg" width ="400">|<img src = "https://user-images.githubusercontent.com/77208067/183234109-ad14d41c-edc8-4651-ac92-0713111ceff2.jpeg" width ="400">|
- Resolved: #631
> [Fix] CompressionQuality 0.5로 수정

- Spark-iOS/Podfile.lock
- Spark-iOS/Spark-iOS.xcodeproj/xcshareddata/xcschemes/Spark-iOS.xcscheme
⛳️ **작업한 브랜치**
- feature/#638
👷 **작업한 내용**
- Xcode 14 업데이트 후 `Stored properties cannot be marked potentially unavailable with @available` 에러를 해결하기 위해서 KakaoSDKAuth 를 업데이트 하였습니다. 다행히 검색해보니 데브톡에서 문의를 통해 Xcode 14 배타버전 때 문제를 발견하여 업데이트를 한 지 좀 되었습니다.
- Xcode 14 로 업데이트하니까 빌드하는 스키마가 초기화되어서 추가했습니다.
- 추가적으로, CocoaPods 업데이트를 진행하였습니다.
> - [Kakao SDK 변경 이력](https://developers.kakao.com/docs/latest/ko/sdk-download/ios#changelog)
> - [데브톡 - Xcode 14 업데이트 빌드 오류 문의](https://devtalk.kakao.com/t/swift5-7-xcode14-beta3/124083)
아래는 Xcode 14 의 릴리즈 노트에서 가져왔습니다.
```
Stored properties in Swift can’t have type information that is potentially unavailable at runtime.
However, prior to Swift 5.7 the compiler incorrectly accepted @available attributes on stored properties when the property had either the lazy modifier …
```
> [Chore] #638 - Xcode 14 업데이트 프로젝트 세팅 업데이트

- Spark-iOS/Spark-iOS/Resource/Constants/Notification.swift
- Spark-iOS/Spark-iOS/Source/AppDelegate.swift
- Spark-iOS/Spark-iOS/Source/SceneDelegate.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthTimer/AuthTimerVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Auth/AuthUpload/AuthUploadVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/CodeJoinVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/CodeJoin/JoinCheckVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateAuthVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Create/CreateSuccessVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/HomeVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/TabBar/MainTBC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/Waiting/WaitingVC.swift
⛳️ **작업한 브랜치**
- feature/#640
👷 **작업한 내용**
- 수빈이가 올린 #641 풀리퀘 코드리뷰 하고 진행하였습니다.
- SceneDelegate 에서 백그라운드 상태에서 푸시알림을 통해 앱에 접근하는 경우에 notification 을 전송하는 코드를 그대로 사용하였습니다.
- 코드리뷰는 다른 의견이었는데 이렇게 해결한 이유는 AppDelegate 에서 진행하면 SplashVC 로의 화면전환을 구현해야하는데 SceneDelegate 에서 진행하면 이미 SplashVC 로의 구현이 되어 있고, 이때 푸시알림을 통해서 접근하는 경우에만 notification 을 전송해주면 되었기 때문입니다.
- `AppDelegate` 에서 분기처리를 진행한 이유는 하지 않으면 background 의 경우에도 중복되어 적용되기 때문이었습니다.
- `HomeVC` 에서 수정사항은 다음과 같습니다.
- 서버에서 recordId 는 "" 빈문자열로 넘어오기 떄문에 nil 값을 가질 수 없습니당. 그래서 조건문자체가 먹히지 않았습니다 🥲
- 삭제한 조건문은 popToHomeVC 를 사용할 시나리오가 없을거라 생각하고 삭제했당! 혹시 제가 놓친 시나리오가 있다면 리뷰해주세용
- #641 풀리퀘와 비교하여 HomeVC 와 AppDelegate 만 수정되었으니 그것만 봐주시면 됩니당
- 이것도 코드리뷰 거쳐서 수빈이가 이 풀리퀘 풀받고, 나머지 코드리뷰도 반영해주면 꼬이지 않을 것 같습니당 🧑‍🏭
|기능|스크린샷|
|:--:|:--:|
|백그라운드에서 습관방|<img src = …
> [Feat] #640 - 푸시알림 카테고리별 화면 전환

- Spark-iOS/Spark-iOS.xcodeproj/project.pbxproj
- Spark-iOS/Spark-iOS/Source/Cells/LifeTimeLine/LifeTimeLineCVC.swift
- Spark-iOS/Spark-iOS/Source/NetworkModels/Room/TimeLine.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomAPI.swift
- Spark-iOS/Spark-iOS/Source/NetworkServices/Room/RoomService.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
- Spark-iOS/Spark-iOS/Source/ViewControllers/LifeTimeLine/LifeTimeLineVC.swift
⛳️ **작업한 브랜치**
- feature/#660
👷 **작업한 내용**
생명 타임라인 API 연결
하다보니까 API쪽에 나중에 좀 깔끔하게 정리할 수 있을 것 같은데 나중에 .. 나중에?
|기능|스크린샷|
|:--:|:--:|
|생명 타임라인|<img src = "https://user-images.githubusercontent.com/81167570/194497627-7871c444-240c-42c7-a2ff-5e8edea34ef2.jpeg" width ="250">|
- Resolved: #660
> [Feat] #660 - 생명 타임라인 API 연결

- Spark-iOS/Spark-iOS/Source/Cells/StorageMore/MoreStorageCVC.swift
⛳️ **작업한 브랜치**
- feature/#617
👷 **작업한 내용**
인증사진 더보기 뷰 이미지 사이즈 large로 변경했습니다.
진작에 할걸.
|기능|스크린샷|
|:--:|:--:|
|GIF|<img src = "https://user-images.githubusercontent.com/77208067/197708945-ea70a00a-9dd9-4f91-ab2a-9eccafb5267d.png" width ="250">|
아래 영상 보시면 알 수 있듯이, large의 경우에 이미지 다운로드 속도가 꽤나 느립니다... 그리고 medium과 큰 차이가 느껴지지 않아서 medium으로 하면 좋을 것 같습니다!
https://user-images.githubusercontent.com/77208067/198308207-ee1adba7-8b5e-4199-b597-dad362e7e7bc.mp4
https://user-images.githubusercontent.com/77208067/198308233-4bad7d4f-42cb-4850-a1b4-c7f3b661885b.mp4
- Resolved: #617
> [Fix] #617 - 인증사진 더보기 뷰 이미지 사이즈 medium로 변경

- Spark-iOS/Spark-iOS/Source/ViewControllers/HabitRoom/HabitRoomVC.swift
⛳️ **작업한 브랜치**
- feature/#682
👷 **작업한 내용**
- QA 과정에서 변경점을 적용하였습니다.
- 불꽃 결정 로드맵 -> 불꽃 결정 레벨
- 노션을 확인해보니 로드맵이라는 단어가 어렵고 거창하다고 해서 레벨로 변경되었습니다.
|기능|스크린샷|
|:--:|:--:|
|불꽃 결정 레벨|<img width="250" alt="스크린샷 2022-11-02 오후 12 33 39" src="https://user-images.githubusercontent.com/69136340/199389210-cde93357-3771-4fd6-b4ec-514febc990bb.png">|
- Resolved: #682
> [Design] #682 - 불꽃 결정 로드맵 이름 변경
